project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
    - "examples/**/*.ipynb"

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: lokigi
  description: "Documentation for the lokigi site optimization package"
  back-to-top-navigation: true
  page-footer:
    center: |
      [![](/lokigi_docs/assets/hsma_logo.png){width=150px}](https://www.hsma.co.uk/)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      [![](/lokigi_docs/assets/nihr_logo.png){width=250px}](https://arc-swp.nihr.ac.uk/)<br/><br/>
      *This work is independent research supported by the National Institute for Health and Care Research Applied Research Collaboration South West Peninsula.<br/>
      The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health and Care Research
      or the Department of Health and Social Care.*
      <br/><br/>
  # 1. TOP NAVIGATION BAR (High-level splits)
  navbar:
    search: true
    left:
      - text: "Home"
        href: lokigi_docs/index.qmd
      - text: "Getting Started"
        href: lokigi_docs/getting_started.qmd
      - text: "Examples"
        href: examples/examples.qmd
      - text: "API Reference"
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/hsma-tools/lokigi/
      - icon: box-fill
        href: https://pypi.org/project/lokigi/

  # 2. SIDEBARS (Context-specific)
  sidebar:
    # --- Sidebar: API Reference (Generated by Quartodoc) ---
    - title: "Reference"
      id: "reference"
      match-path: "reference/*" # Matches the quartodoc output dir
      contents:
        - _sidebar.yml # Include the file quartodoc generates
      style: floating


# 3. QUARTODOC CONFIGURATION (Purely for API)
quartodoc:
  dir: reference
  out_index: index.qmd
  package: lokigi
  options:
    include_inherited: true
    include_imports: true
    dynamic: true

  # Write the API structure to this file
  sidebar:
    file: "_sidebar.yml"
    style: floating
    collapse-level: 3
    # ONLY include the placeholder here. We moved the manual stuff up to `website`
    contents:
      - "{{ contents }}"

  # Define the Python objects to document
  sections:
    - title: Location Optimization Problem Classes
      desc: ""
      contents:
        - name: site.SiteProblem
          children: separate
        - name: site.EvaluatedCombination
        - name: site.SiteSolutionSet
          children: separate
          members:
            # Note that every new method must be manually listed here
            # due to the use of mixins and them not being picked up if
            # not explicitly included
            - show_solutions
            - return_best_combination_details
            - return_best_combination_site_indices
            - return_best_combination_site_names
            - plot_simple_pareto_front
            - plot_all_metric_pareto_front
            - plot_n_best_combinations_bar
            - plot_best_combination
            - plot_n_best_combinations
            - plot_travel_time_distribution
            - check_solution_equity
            - plot_top_n_solution_equity
            - plot_combination_by_equity
    # - title: lokigi boundary classes
    #   desc: ""
    #   contents:
    #     - problem.BoundaryProblem
    #     - problem.BoundarySolution

format:
  html:
    grid:
      sidebar-width: 325px
      body-width: 1200px
      margin-width: 250px
      gutter-width: 1.5rem
    execute:
      freeze: auto
    theme:
      dark: [darkly, lokigi_docs/resources/theme-dark.scss]
      light: [flatly, lokigi_docs/resources/theme-light.scss]
    css: lokigi_docs/resources/styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
