"""
Code in this file has primarily been generated by Claude Sonnet 4.6, and Gemini 3.1 Pro,
with appropriate review and adjustment by a human.
"""

import warnings
from typing import Literal
import pandas as pd

import esda
from pysal.lib import weights

import contextily as cx
import folium
import geopandas

import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import matplotlib.colors as mcolors

import warnings
from requests.exceptions import RequestException


NeighbourhoodMethod = Literal[
    "rook",
    "queen",
    "k-nearest",
]

ClusterDisplay = Literal[
    "all",
    "hotspots",
    "coldspots",
    "outliers",
]

SupportedProblemInputs = Literal["demand", "equity", "demand_equity"]

SupportedSolutionInputs = Literal[
    "demand",
    "equity",
    "demand_equity",
    "travel_demand",
    "travel_equity",
]

SupportedInputs = SupportedProblemInputs | SupportedSolutionInputs

SupportedCombinationMethods = Literal["multiply", "sum", "rank"]

TypologyBins = Literal[2, 3]


# MARK: Shared functions
@staticmethod
def _minmax(series: pd.Series) -> pd.Series:
    mn, mx = series.min(), series.max()
    return pd.Series(0.5, index=series.index) if mx == mn else (series - mn) / (mx - mn)


# MARK: Weights
class SiteProblemEDAMixin:
    @property
    def _prob_ctx(self):
        """
        Dynamically routes requests to the object holding the problem data.
        Returns 'self.site_problem' if attached to a SiteSolutionSet,
        otherwise returns 'self' if attached directly to a Problem.
        """
        return getattr(self, "site_problem", self)

    def _get_weights(
        self,
        df,
        neighbourhood_method: NeighbourhoodMethod = "rook",
        k: int | None = None,
        verbose: bool = True,
        return_weights: bool = True,
        force_recalculation: bool = True,
    ):
        """
        Create and cache a spatial weights matrix.

        Generates a PySAL spatial weights object based on the region
        geometry layer attached to the problem. The resulting weights
        matrix is row-standardised and cached for reuse by exploratory
        spatial data analysis methods.

        Parameters
        ----------
        neighbourhood_method : {"rook", "queen", "k-nearest"}, default="rook"
            Method used to define neighbouring regions.

            * ``"rook"``: Regions sharing an edge are considered neighbours.
            * ``"queen"``: Regions sharing an edge or vertex are considered
            neighbours.
            * ``"k-nearest"``: Each region is connected to its ``k`` nearest
            neighbours.

        k : int, optional
            Number of neighbours to use when ``neighbourhood_method="k-nearest"``.
            Ignored for rook and queen contiguity.

        Raises
        ------
        ValueError
            If ``neighbourhood_method="k-nearest"`` and ``k`` is not provided.

        Notes
        -----
        The resulting weights matrix is row-standardised using
        ``w.transform = "R"``.

        The weights matrix and metadata describing how it was generated
        are stored on the instance as:

        * ``self.spatial_weights``
        * ``self.spatial_weights_method``
        * ``self.spatial_weights_k``
        """
        valid_neighbourhood_method = ["rook", "queen", "k-nearest"]

        if neighbourhood_method not in valid_neighbourhood_method:
            raise ValueError(
                f"neighbourhood_method must be one of {valid_neighbourhood_method}, got {neighbourhood_method!r}"
            )
        # Get the unified context object, meaning we handle this appropriately
        # regardless of whether this is a Problem or SiteSolutionSet
        ctx = self._prob_ctx

        # We look at the hash for the entire region geometry as we're just trying to capture
        # if the region geometry has changed, not whether it's the same region requested as
        # before
        current_hash = ctx._get_geometry_hash(ctx.region_geometry_layer)

        if (
            ctx.spatial_weights is None
            or neighbourhood_method != ctx.spatial_weights_method
            or k != ctx.spatial_weights_k
            or current_hash != ctx._region_geometry_hash
            or force_recalculation
        ):
            if neighbourhood_method == "queen":
                w = weights.Queen.from_dataframe(df)
            elif neighbourhood_method == "rook":
                w = weights.Rook.from_dataframe(df)
            elif neighbourhood_method == "k-nearest":
                if k is None:
                    raise ValueError(
                        "Please specify a value of k in get_hotspots if you want to use k-nearest neighbours"
                    )
                w = weights.KNN.from_dataframe(df, k=k)

            w.transform = "R"

            ctx.spatial_weights = w
            ctx.spatial_weights_method = neighbourhood_method
            ctx.spatial_weights_k = k
            ctx._region_geometry_hash = current_hash
        else:
            if verbose:
                warnings.warn(
                    "Using cached spatial weights.",
                    stacklevel=2,
                )

        if return_weights:
            return ctx.spatial_weights


# MARK: Problem-level Calculations
class SiteProblemHotspotCalculationMixin:
    @property
    def _prob_ctx(self):
        return getattr(self, "site_problem", self)

    def _prepare_analysis_dataframe(
        self,
        what: str,
        combination_method: str,
        n_bins: TypologyBins = 3,  # Parameter to support 2x2 or 3x3 matrices
    ) -> tuple[pd.DataFrame, str, str]:
        """
        Base data-prep method. Handles standard Problem-level fields.
        Returns: (working_dataframe, column_to_analyze, id_merge_column)
        """
        ctx = self._prob_ctx

        if what == "demand":
            df = ctx.demand_data.copy()
            return df, ctx._demand_data_demand_col, ctx._demand_data_id_col

        elif what == "equity":
            df = ctx.equity_data.copy()
            df_col = ctx._equity_data_equity_col
            df_merge_col = ctx._equity_data_common_col

            # Filter to active demand IDs
            df = df[
                df[df_merge_col].isin(ctx.demand_data[ctx._demand_data_id_col].unique())
            ]

            if ctx._equity_data_direction == "higher_is_worse":
                analysis_col = f"_{df_col}_analysis"
                df[analysis_col] = -df[df_col]
                df_col = analysis_col
            return df, df_col, df_merge_col

        elif what == "demand_equity":
            if ctx.equity_data is None:
                raise ValueError("No equity data loaded. Call add_equity_data() first.")

            # --- Align & Merge (using ctx attributes) ---
            demand_df = ctx.demand_data.copy()
            equity_df = ctx.equity_data.copy()
            shared_ids = demand_df[ctx._demand_data_id_col].unique()
            equity_df = equity_df[
                equity_df[ctx._equity_data_common_col].isin(shared_ids)
            ]

            equity_col = ctx._equity_data_equity_col
            if ctx._equity_data_direction == "higher_is_worse":
                equity_df["_equity_directed"] = -equity_df[equity_col]
            else:
                equity_df["_equity_directed"] = equity_df[equity_col]

            df = demand_df.merge(
                equity_df[
                    [ctx._equity_data_common_col, "_equity_directed", equity_col]
                ],
                left_on=ctx._demand_data_id_col,
                right_on=ctx._equity_data_common_col,
                how="inner",
                suffixes=("", "_y"),
            )

            df = df.drop(df.filter(regex="_y$").columns, axis=1)

            df["_demand_norm"] = _minmax(df[ctx._demand_data_demand_col])
            df["_equity_norm"] = _minmax(df["_equity_directed"])

            # --- Combined Scoring ---
            if combination_method == "multiply":
                df["combined_score"] = df["_demand_norm"] * df["_equity_norm"]
            elif combination_method == "sum":
                df["combined_score"] = (df["_demand_norm"] + df["_equity_norm"]) / 2
            elif combination_method == "rank":
                df["combined_score"] = (
                    df["_demand_norm"].rank() + df["_equity_norm"].rank()
                ) / (2 * len(df))
            else:
                raise ValueError(f"Invalid combination_method: {combination_method}")

            # --- MARK: Dynamic Typology Calculation ---
            if n_bins == 2:
                demand_labels, equity_labels = ["Low", "High"], ["Low", "High"]
            elif n_bins == 3:
                demand_labels, equity_labels = (
                    ["Low", "Medium", "High"],
                    ["Low", "Medium", "High"],
                )
            else:
                raise ValueError("n_bins must be 2 or 3.")

            df["demand_level"] = pd.qcut(
                df["_demand_norm"], q=n_bins, labels=demand_labels
            )
            df["equity_level"] = pd.qcut(
                df["_equity_norm"], q=n_bins, labels=equity_labels
            )

            df["attribute_typology"] = (
                df["demand_level"].astype(str)
                + " Demand / "
                + df["equity_level"].astype(str)
                + " Deprivation"
            )

            return df, "combined_score", ctx._demand_data_id_col

        raise ValueError(f"Unsupported analysis input type: '{what}'")

    def get_hotspots(
        self,
        what: str = "demand",
        neighbourhood_method: str = "rook",
        combination_method: str = "multiply",
        k: int | None = None,
        verbose: bool = True,
        significance_threshold: float = 0.05,
        force_weight_recalculation: bool = False,
        n_bins: TypologyBins = 3,
    ):
        """
        Identify statistically significant hotspots and coldspots.

        Returns hotspot, coldspot, outlier and non-significant classifications
        derived from Local Moran's I.

        Performs local spatial autocorrelation analysis on a selected
        variable using the specified spatial weights matrix. Areas with
        significantly high values surrounded by high values are classified
        as hotspots, while areas with significantly low values surrounded
        by low values are classified as coldspots.

        Parameters
        ----------
        what : str, default="demand"
            Variable to analyse. This may be the name of a stored dataset
            or metric associated with the problem, such as demand,
            accessibility, or equity measures.

        neighbourhood_method : {"rook", "queen", "k-nearest"}, default="rook"
            Method used to define neighbouring regions.

        k : int, optional
            Number of neighbours to use when ``neighbourhood_method="k-nearest"``.
            Required if ``neighbourhood_method="k-nearest"``.

        Returns
        -------
        geopandas.GeoDataFrame
            Region geometry layer with additional columns describing
            hotspot/coldspot classification and associated statistics.

        Notes
        -----
        Spatial weights are generated when required and cached for
        reuse. Cached weights are automatically invalidated when the
        region geometry or weighting parameters change.
        """
        # Build the weights if they've not been generated before or if anything about
        # the weight parameters or region geometry layer have changed

        # Demand is assumed to only be passed for the region of interest.
        # In effect, it's expected to define the region of interest!
        # And this holds if you are generating a problem simply from a travel matrix without
        # passing in demand (although then you're not going to be looking for demand hotspots,
        # though you could be interested in equity hotspots)
        # However, there's a good chance you'll have passed an unfiltered whole-country
        # equity dataset, so this needs to filter down too.

        ctx = self._prob_ctx

        # 1. Delegate data prep out to the extensible method
        df, df_col, df_merge_col = self._prepare_analysis_dataframe(
            what, combination_method, n_bins=n_bins
        )
        result = df.copy()

        # 2. Geometry Filtering
        filtered_region_geometry = ctx.region_geometry_layer.copy()
        filtered_region_geometry = filtered_region_geometry[
            filtered_region_geometry[ctx._region_geometry_layer_common_col].isin(
                ctx.demand_data[ctx._demand_data_id_col].unique()
            )
        ]

        # 3. Weights Resolution
        w = self._get_weights(
            df=filtered_region_geometry,
            neighbourhood_method=neighbourhood_method,
            k=k,
            verbose=verbose,
            return_weights=True,
            force_recalculation=force_weight_recalculation,
        )

        # 4. Local Moran's I Core Math Engine
        lisa = esda.moran.Moran_Local(result[df_col], w)

        result["local_moran_i"] = lisa.Is
        result["p_value"] = lisa.p_sim
        result["quadrant"] = lisa.q
        result["cluster_type"] = "Not Significant"

        significant = lisa.p_sim < significance_threshold
        result.loc[significant & (lisa.q == 1), "cluster_type"] = "Hotspot"
        result.loc[significant & (lisa.q == 3), "cluster_type"] = "Coldspot"
        result.loc[significant & (lisa.q == 2), "cluster_type"] = "Low-High Outlier"
        result.loc[significant & (lisa.q == 4), "cluster_type"] = "High-Low Outlier"

        # Cleanup working columns
        result = result.drop(
            columns=["_demand_norm", "_equity_norm", "_equity_directed"],
            errors="ignore",
        )

        df = ctx.region_geometry_layer.merge(
            result,
            left_on=ctx._region_geometry_layer_common_col,
            right_on=df_merge_col,
            suffixes=("", "_y"),
        )

        return df.drop(df.filter(regex="_y$").columns, axis=1)


# MARK: Solution-level Calculations
class SiteSolutionHotspotCalculationMixin(SiteProblemHotspotCalculationMixin):
    """
    Overrides data preparation to inject solution-specific travel time metrics.

    Supports two additional ``what`` values beyond the base problem:

    - ``"travel_demand"`` : combined minimum travel time + demand.
    - ``"travel_equity"`` : combined minimum travel time + equity (IMD etc.).

    In all travel-time cases, ``min_cost`` is treated as ``higher_is_worse``
    (lower travel time = better access), so the negation is applied
    automatically before any combination or Moran's I calculation.

    A specific solution row is selected via ``solution_rank``. If multiple
    rows share the same rank, the first is used and a warning is raised.
    """

    @property
    def _prob_ctx(self):
        """
        Dynamically routes requests to the object holding the problem data.
        Returns 'self.site_problem' if attached to a SiteSolutionSet,
        otherwise returns 'self' if attached directly to a Problem.
        """
        return getattr(self, "site_problem", self)

    def _get_solution_travel_times(self, solution_rank: int) -> pd.DataFrame:
        """
        Extract min_cost for the selected solution rank, merged-ready.

        Returns a DataFrame with [LSOA id col, "_travel_time_directed"] where
        the travel time has already been negated (lower = better = higher score).

        Parameters
        ----------
        solution_rank : int
            The rank of the solution to select from ``self.solution_df``.

        Returns
        -------
        pd.DataFrame

        Warns
        -----
        UserWarning
            If multiple rows share ``solution_rank``; the first is used.
        """
        ctx = self._prob_ctx
        id_col = ctx._region_geometry_layer_common_col

        ranked = self.solution_df[self.solution_df["solution_rank"] == solution_rank]

        if ranked.empty:
            raise ValueError(f"No solution found with solution_rank={solution_rank}.")
        if len(ranked) > 1:
            warnings.warn(
                f"Multiple solutions share solution_rank={solution_rank}. "
                "Using the first. Consider breaking ties before analysis.",
                UserWarning,
                stacklevel=3,
            )

        # Unpack the nested problem_df from the selected solution row
        problem_df = ranked.iloc[0]["problem_df"]

        if id_col not in problem_df.columns:
            raise KeyError(
                f"Expected ID column '{id_col}' not found in nested problem_df. "
                f"Available columns: {problem_df.columns.tolist()}"
            )
        if "min_cost" not in problem_df.columns:
            raise KeyError(
                f"'min_cost' not found in nested problem_df. "
                f"Available columns: {problem_df.columns.tolist()}"
            )

        travel_df = (
            problem_df[[id_col, "min_cost"]].copy().drop_duplicates(subset=id_col)
        )

        # In _get_solution_travel_times — return raw min_cost, no negation
        travel_df["_travel_time_directed"] = travel_df["min_cost"]  # no negation here

        return travel_df[[id_col, "_travel_time_directed", "min_cost"]]

    def _prepare_analysis_dataframe(
        self,
        what: str,
        combination_method: str,
        solution_rank: int = 1,
        n_bins: TypologyBins = 3,
    ) -> tuple[pd.DataFrame, str, str]:
        """
        Extends base data preparation with solution-specific travel metrics.

        Parameters
        ----------
        what : str
            One of ``"demand"``, ``"equity"``, ``"demand_equity"``
            (inherited), or ``"travel_demand"``,
            ``"travel_equity"`` (solution-specific).
        combination_method : str
            Passed through to the base class for combined analyses.
        solution_rank : int, default 1
            Rank of the solution row to use from ``self.solution_df``.
        n_bins : int, default 3
            Number of quantiles to split the typologies into (2 for halves, 3 for thirds).

        Returns
        -------
        tuple[pd.DataFrame, str, str]
            Working dataframe, column to analyse, ID merge column.
        """
        # Pass n_bins up to the super class if you implement it there too!
        if what not in ("travel_demand", "travel_equity"):
            return super()._prepare_analysis_dataframe(
                what, combination_method, n_bins=n_bins
            )

        ctx = self._prob_ctx
        demand_id_col = ctx._demand_data_id_col
        geometry_id_col = ctx._region_geometry_layer_common_col

        travel_df = self._get_solution_travel_times(solution_rank)

        # ---------------------------------------------------------
        # TRAVEL DEMAND
        # ---------------------------------------------------------
        if what == "travel_demand":
            demand_df = ctx.demand_data.merge(
                travel_df,
                left_on=demand_id_col,
                right_on=geometry_id_col,
                how="inner",
                suffixes=("", "_y"),
            )
            demand_df = demand_df.drop(demand_df.filter(regex="_y$").columns, axis=1)

            demand_df["_demand_norm"] = _minmax(demand_df[ctx._demand_data_demand_col])
            demand_df["_travel_norm"] = _minmax(demand_df["_travel_time_directed"])

            if combination_method == "multiply":
                demand_df["combined_score"] = (
                    demand_df["_demand_norm"] * demand_df["_travel_norm"]
                )
            elif combination_method == "sum":
                demand_df["combined_score"] = (
                    demand_df["_demand_norm"] + demand_df["_travel_norm"]
                ) / 2
            elif combination_method == "rank":
                demand_df["combined_score"] = (
                    demand_df["_demand_norm"].rank() + demand_df["_travel_norm"].rank()
                ) / (2 * len(demand_df))
            else:
                raise ValueError(f"Invalid combination_method: '{combination_method}'")

            # Dynamic Typology Assignment
            if n_bins == 2:
                demand_labels, access_labels = ["Low", "High"], ["Good", "Poor"]
            elif n_bins == 3:
                demand_labels, access_labels = (
                    ["Low", "Medium", "High"],
                    ["Good", "Medium", "Poor"],
                )
            else:
                raise ValueError("n_bins must be 2 or 3.")

            # qcut automatically handles the ascending order.
            # Lowest travel norm = "Good", highest = "Poor"
            demand_df["demand_level"] = pd.qcut(
                demand_df["_demand_norm"], q=n_bins, labels=demand_labels
            )
            demand_df["access_level"] = pd.qcut(
                demand_df["_travel_norm"], q=n_bins, labels=access_labels
            )

            demand_df["attribute_typology"] = (
                demand_df["demand_level"].astype(str)
                + " Demand / "
                + demand_df["access_level"].astype(str)
                + " Access"
            )

            return demand_df, "combined_score", geometry_id_col

        # ---------------------------------------------------------
        # TRAVEL EQUITY
        # ---------------------------------------------------------
        elif what == "travel_equity":
            if ctx.equity_data is None:
                raise ValueError("No equity data loaded. Call add_equity_data() first.")

            equity_df = ctx.equity_data.copy()
            equity_col = ctx._equity_data_equity_col

            if ctx._equity_data_direction == "higher_is_worse":
                equity_df["_equity_directed"] = -equity_df[equity_col]
            else:
                equity_df["_equity_directed"] = equity_df[equity_col]

            df = ctx.demand_data[[demand_id_col]].merge(
                travel_df,
                left_on=demand_id_col,
                right_on=geometry_id_col,
                how="inner",
                suffixes=("", "_y"),
            )
            df = df.drop(df.filter(regex="_y$").columns, axis=1)

            df = df.merge(
                equity_df[
                    [ctx._equity_data_common_col, "_equity_directed", equity_col]
                ],
                left_on=geometry_id_col,
                right_on=ctx._equity_data_common_col,
                how="inner",
                suffixes=("", "_y"),
            )
            df = df.drop(df.filter(regex="_y$").columns, axis=1)

            df["_travel_norm"] = _minmax(df["_travel_time_directed"])
            df["_equity_norm"] = _minmax(df["_equity_directed"])

            if combination_method == "multiply":
                df["combined_score"] = df["_travel_norm"] * df["_equity_norm"]
            elif combination_method == "sum":
                df["combined_score"] = (df["_travel_norm"] + df["_equity_norm"]) / 2
            elif combination_method == "rank":
                df["combined_score"] = (
                    df["_travel_norm"].rank() + df["_equity_norm"].rank()
                ) / (2 * len(df))
            else:
                raise ValueError(f"Invalid combination_method: '{combination_method}'")

            # Dynamic Typology Assignment
            if n_bins == 2:
                equity_labels, access_labels = ["Low", "High"], ["Good", "Poor"]
            elif n_bins == 3:
                equity_labels, access_labels = (
                    ["Low", "Medium", "High"],
                    ["Good", "Medium", "Poor"],
                )
            else:
                raise ValueError("n_bins must be 2 or 3.")

            df["equity_level"] = pd.qcut(
                df["_equity_norm"], q=n_bins, labels=equity_labels
            )
            df["access_level"] = pd.qcut(
                df["_travel_norm"], q=n_bins, labels=access_labels
            )

            df["attribute_typology"] = (
                df["equity_level"].astype(str)
                + " Deprivation / "
                + df["access_level"].astype(str)
                + " Access"
            )

            return df, "combined_score", geometry_id_col

    def get_hotspots(
        self,
        what="demand",
        combination_method="multiply",
        solution_rank=1,
        n_bins: TypologyBins = 3,
        **kwargs,
    ):
        """
        prepare_analysis_dataframe now takes solution_rank as a parameter, which means get_hotspots
        in the solution class needs to accept and pass it through too. The base class signature
        doesn't need it, so override get_hotspots in the solution mixin to add it.
        """
        # store rank so _prepare_analysis_dataframe can access it,
        # or pass explicitly depending on your call chain structure
        self._active_solution_rank = solution_rank
        return super().get_hotspots(
            what=what, combination_method=combination_method, n_bins=n_bins, **kwargs
        )


class HotspotPlotMixin:
    @property
    def _prob_ctx(self):
        """
        Dynamically routes requests to the object holding the problem data.
        Returns 'self.site_problem' if attached to a SiteSolutionSet,
        otherwise returns 'self' if attached directly to a Problem.
        """
        return getattr(self, "site_problem", self)

    # MARK: HOTSPOT map
    def plot_hotspots(
        self,
        hotspots_df: pd.DataFrame | None = None,
        ax: plt.Axes | None = None,
        interactive: bool = False,
        show_hotspots: bool = True,
        show_coldspots: bool = True,
        show_low_high_outliers: bool = True,
        show_high_low_outliers: bool = True,
        show_non_significance: bool = True,
        hotspot_colour: str = "#d7191c",  # red
        coldspot_colour: str = "#2c7bb6",  # dark blue
        low_high_outlier_colour: str = "#abd9e9",  # light blue
        high_low_outlier_colour: str = "#fee08b",  # yellow
        not_significant_colour: str = "#bdbdbd",  # grey
        tiles: str = "CartoDB positron",
        edgecolor: str = "black",
        linewidth: float = 0.5,
        show_basemap: bool = True,
        show_axis: bool = False,
        opacity: float = 0.7,
        what: SupportedInputs = "demand",
        combination_method: SupportedCombinationMethods = "multiply",
        neighbourhood_method: NeighbourhoodMethod = "rook",
        k: int | None = None,
        verbose: bool = True,
        significance_threshold: float = 0.05,
        force_weight_recalculation: bool = False,
        figsize: tuple | None = None,
        **kwargs,
    ):
        """
        Plot statistically significant hotspots and coldspots.

        Creates either a static GeoPandas choropleth or an interactive
        Folium map showing the results of Local Moran's I analysis.
        Areas are coloured according to hotspot classification.

        Parameters
        ----------
        hotspots_df : geopandas.GeoDataFrame, optional
            Hotspot analysis results returned by :meth:`get_hotspots`.
            If ``None``, hotspot analysis is performed automatically
            using the supplied parameters.

        interactive : bool, default=False
            If ``True``, return an interactive Folium map. Otherwise,
            return a static GeoPandas plot.

        hotspot_colour : str, default="#d7191c"
            Colour used for statistically significant hotspot
            (high-high) regions.

        coldspot_colour : str, default="#2c7bb6"
            Colour used for statistically significant coldspot
            (low-low) regions.

        low_high_outlier_colour : str, default="#abd9e9"
            Colour used for low-high spatial outliers.

        high_low_outlier_colour : str, default="#fee08b"
            Colour used for high-low spatial outliers.

        not_significant_colour : str, default="#bdbdbd"
            Colour used for regions that are not statistically
            significant.

        tiles : str, default="CartoDB positron"
            Tile provider used for interactive maps.

        edgecolor : str, default="black"
            Boundary colour used when plotting polygons.

        linewidth : float, default=0.5
            Width of polygon boundaries.

        what : {"demand", "equity"}, default="demand"
            Variable used for hotspot analysis when
            ``hotspots_df`` is not provided.

        neighbourhood_method : {"rook", "queen", "k-nearest"}, default="rook"
            Method used to define neighbouring regions.

        k : int, optional
            Number of neighbours when
            ``neighbourhood_method="k-nearest"``.

        verbose : bool, default=True
            Whether to print progress information.

        significance_threshold : float, default=0.05
            Significance threshold used to classify hotspot and
            coldspot regions.

        force_weight_recalculation : bool, default=False
            If ``True``, spatial weights are recalculated even if a
            cached version is available.

        figsize: tuple, default None
            Allow overriding size of static plot

        **kwargs
            Additional keyword arguments passed to
            ``GeoDataFrame.plot`` or ``GeoDataFrame.explore``.

        Returns
        -------
        matplotlib.axes.Axes or folium.Map
            Static or interactive hotspot map depending on the value
            of ``interactive``.

        Notes
        -----
        Hotspot classifications are derived from Local Moran's I and
        consist of:

        * Hotspot (high-high)
        * Coldspot (low-low)
        * Low-high spatial outlier
        * High-low spatial outlier
        * Not significant

        The default colour scheme mirrors the conventions commonly
        used in GeoDa and PySAL visualisations.
        """

        # Get the unified context object, meaning we handle this appropriately
        # regardless of whether this is a Problem or SiteSolutionSet
        ctx = self._prob_ctx

        if hotspots_df is None:
            hotspots_df = self.get_hotspots(
                what=what,
                neighbourhood_method=neighbourhood_method,
                combination_method=combination_method,
                k=k,
                verbose=verbose,
                significance_threshold=significance_threshold,
                force_weight_recalculation=force_weight_recalculation,
            )

        is_combined = "attribute_typology" in hotspots_df.columns

        # Determine which tooltip fields are available — attribute_typology
        # is only present for combined runs
        _base_tooltip_fields = [
            "cluster_type",
            ctx._region_geometry_layer_common_col,
            "local_moran_i",
            "p_value",
            "quadrant",
        ]
        _base_tooltip_aliases = [
            "Cluster",
            "Region",
            "Local Moran I",
            "p-value",
            "Quadrant",
        ]

        if "attribute_typology" in (
            hotspots_df.columns if hotspots_df is not None else []
        ):
            _tooltip_fields = ["attribute_typology"] + _base_tooltip_fields
            _tooltip_aliases = ["Attribute Typology"] + _base_tooltip_aliases
        else:
            _tooltip_fields = _base_tooltip_fields
            _tooltip_aliases = _base_tooltip_aliases

        def add_cluster_layer(
            df, cluster_name, group_name, colour, visible, opacity, edgecolor
        ):
            subset = df[df["cluster_type"] == cluster_name]

            if subset.empty:
                return

            fg = folium.FeatureGroup(name=group_name, show=visible)

            folium.GeoJson(
                subset,
                style_function=lambda feature, c=colour: {
                    "fillColor": c,
                    "color": edgecolor,
                    "weight": linewidth,
                    "fillOpacity": opacity,
                },
                tooltip=folium.GeoJsonTooltip(
                    fields=_tooltip_fields,
                    aliases=_tooltip_aliases,
                ),
            ).add_to(fg)

            fg.add_to(m)

        cluster_groups = {
            "Hotspot": "Hotspots",
            "Coldspot": "Coldspots",
            "Low-High Outlier": "Low-High Outliers",
            "High-Low Outlier": "High-Low Outliers",
            "Not Significant": "Not Significant",
        }

        visible = {
            "Hotspot": show_hotspots,
            "Coldspot": show_coldspots,
            "Low-High Outlier": show_low_high_outliers,
            "High-Low Outlier": show_high_low_outliers,
            "Not Significant": show_non_significance,
        }

        colours = {
            "Hotspot": hotspot_colour,
            "Coldspot": coldspot_colour,
            "Low-High Outlier": low_high_outlier_colour,
            "High-Low Outlier": high_low_outlier_colour,
            "Not Significant": not_significant_colour,
        }

        hotspots_df["_alpha"] = hotspots_df["cluster_type"].map(
            lambda c: opacity if visible.get(c, False) else 0.0
        )

        if interactive:
            hotspots_df["_plot_colour"] = hotspots_df.apply(
                lambda r: (
                    colours[r["cluster_type"]]
                    if visible.get(r["cluster_type"], False)
                    else "#e6e6e6"  # light grey for hidden categories
                ),
                axis=1,
            )

            # Get bounds from the GeoDataFrame to centre the map correctly
            bounds = hotspots_df.to_crs(
                epsg=4326
            ).total_bounds  # [minx, miny, maxx, maxy]
            centre = [(bounds[1] + bounds[3]) / 2, (bounds[0] + bounds[2]) / 2]

            m = folium.Map(
                location=centre,
                tiles=tiles if show_basemap else None,
            )

            for cluster_name, group_name in cluster_groups.items():
                add_cluster_layer(
                    hotspots_df,
                    cluster_name,
                    group_name,
                    colour=colours[cluster_name],
                    visible=visible[cluster_name],
                    opacity=opacity,
                    edgecolor=edgecolor,
                )

            folium.LayerControl(collapsed=False).add_to(m)

            # Fit the map to the data extent
            m.fit_bounds([[bounds[1], bounds[0]], [bounds[3], bounds[2]]])

            return m
        else:
            hotspots_df["_plot_colour"] = hotspots_df["cluster_type"].map(colours)

            hotspots_df["_plot_rgba"] = hotspots_df.apply(
                lambda r: mcolors.to_rgba(
                    r["_plot_colour"],
                    r["_alpha"],
                ),
                axis=1,
            )

            if ax is None:
                fig, ax = plt.subplots(
                    figsize=figsize or (10, 10), layout="constrained"
                )

            ax = hotspots_df.plot(
                ax=ax,
                legend=True,
                color=hotspots_df["_plot_rgba"],
                edgecolor=edgecolor,
                linewidth=linewidth,
                **kwargs,
            )

            handles = [
                Patch(facecolor=colour, label=label)
                for label, colour in colours.items()
            ]

            ax.legend(
                handles=handles,
                title="Cluster Type",
                loc="best",
            )

            if is_combined:
                ax.set_title(
                    f"Combined Demand / Deprivation Hotspots ({combination_method})",
                    fontsize=10,
                )

            if show_basemap:
                try:
                    cx.add_basemap(ax, crs=hotspots_df.crs.to_string(), timeout=30)
                except RequestException as e:
                    warnings.warn(
                        f"Unable to download background map tiles ({type(e).__name__}). "
                        "Continuing without a basemap.",
                        stacklevel=2,
                    )

            if not show_axis:
                ax.axis("off")

            return ax

    # MARK: QUADRANT MAP
    def plot_quadrant_map(
        self,
        hotspots_df: geopandas.GeoDataFrame | None = None,
        what: SupportedInputs | None = "demand_equity",
        n_bins: TypologyBins = 3,
        ax: plt.Axes | None = None,
        interactive: bool = False,
        combination_method: Literal["multiply", "sum", "rank"] = "multiply",
        neighbourhood_method: NeighbourhoodMethod = "rook",
        k: int | None = None,
        verbose: bool = True,
        significance_threshold: float = 0.05,  # Only used if n_bins = 2
        force_weight_recalculation: bool = False,
        # Typology colours — 2x2 quadrant palette
        priority_colour: str = "#d7191c",  # red   — needs intervention
        concerning_colour: str = "#fdae61",  # amber — worth monitoring
        positive_colour: str = "#2c7bb6",  # blue  — doing well
        neutral_colour: str = "#bdbdbd",  # grey  — baseline, no action needed
        # Significance overlay
        significant_edgecolor: str = "#1a1a1a",
        significant_linewidth: float = 1.8,
        non_significant_edgecolor: str = "#bbbbbb",
        non_significant_linewidth: float = 0.4,
        tiles: str = "CartoDB positron",
        show_basemap: bool = True,
        show_axis: bool = False,
        opacity: float = 0.7,
        # Legend placement
        legend_loc: str = "outside",  # "outside" | any matplotlib loc string e.g. "lower left"
        legend_bbox_to_anchor: tuple | None = None,  # overrides default when set
        figsize: tuple | None = None,
        **kwargs,
    ):
        """
        Plot the 2×2 attribute typology for a combined demand/deprivation analysis.

        Each area is coloured according to whether it is high or low on demand
        and deprivation independently (the ``attribute_typology`` column produced
        by :meth:`get_hotspots` with ``what="demand_equity"``). Areas that are also
        statistically significant spatial clusters (Hotspot or Coldspot) are
        additionally highlighted with a bolder border.

        This plot complements :meth:`plot_hotspots`: where that method shows
        *spatial clustering*, this one shows the underlying *attribute structure*
        — i.e. why an area is (or is not) a hotspot.

        Parameters
        ----------
        hotspots_df : geopandas.GeoDataFrame, optional
            Pre-computed results from :meth:`get_hotspots` with
            ``what="demand_equity"``. If ``None``, the analysis is run automatically
            using the supplied parameters.
        n_bins : int, default 3
            Number of quantiles to split the typologies into (2 for halves, 3 for thirds).
        ax : matplotlib.axes.Axes, optional
            Axes to plot on. A new figure and axes are created if not provided.
            Ignored when ``interactive=True``.
        interactive : bool, default False
            If ``True``, returns an interactive Folium map. Otherwise returns
            a static matplotlib axes.
        combination_method : {"multiply", "sum", "rank"}, default "multiply"
            Score combination method passed to :meth:`get_hotspots` when
            ``hotspots_df`` is ``None``.
        neighbourhood_method : {"rook", "queen", "k-nearest"}, default "rook"
            Spatial weights method passed to :meth:`get_hotspots` when
            ``hotspots_df`` is ``None``.
        k : int, optional
            Number of neighbours for ``neighbourhood_method="k-nearest"``.
        verbose : bool, default True
            Whether to print progress when recomputing hotspots.
        significance_threshold : float, default 0.05
            P-value threshold used to determine which areas receive a bold
            significance border.
        force_weight_recalculation : bool, default False
            If ``True``, spatial weights are recalculated even if cached.
        priority_colour : str, default "#d7191c"
            Colour for High Demand / High Deprivation areas.
        concerning_colour : str, default "#fee08b"
            Colour for High Demand / Low Deprivation areas.
        positive_colour : str, default "#abd9e9"
            Colour for Low Demand / High Deprivation areas.
        neutral_colour : str, default "#bdbdbd"
            Colour for Low Demand / Low Deprivation areas.
        significant_edgecolor : str, default "#1a1a1a"
            Border colour for statistically significant spatial clusters.
        significant_linewidth : float, default 1.8
            Border width for statistically significant spatial clusters.
        non_significant_edgecolor : str, default "#bbbbbb"
            Border colour for non-significant areas.
        non_significant_linewidth : float, default 0.4
            Border width for non-significant areas.
        tiles : str, default "CartoDB positron"
            Tile provider for interactive maps.
        show_basemap : bool, default True
            Whether to add a basemap (static) or tile layer (interactive).
        show_axis : bool, default False
            Whether to show axis ticks and labels on static plots.
        opacity : float, default 0.7
            Fill opacity for all areas.
        figsize: tuple, default None
            Allow overriding size of static plot
        **kwargs
            Additional keyword arguments passed to ``GeoDataFrame.plot``
            or ``GeoDataFrame.explore``.

        Returns
        -------
        matplotlib.axes.Axes or folium.Map

        Raises
        ------
        ValueError
            If ``hotspots_df`` is provided but does not contain an
            ``attribute_typology`` column, suggesting it was not produced
            by a combined analysis.
        """
        # Get the unified context object, meaning we handle this appropriately
        # regardless of whether this is a Problem or SiteSolutionSet
        ctx = self._prob_ctx

        if hotspots_df is None:
            hotspots_df = self.get_hotspots(
                what=what,
                combination_method=combination_method,
                neighbourhood_method=neighbourhood_method,
                k=k,
                verbose=verbose,
                significance_threshold=significance_threshold,
                force_weight_recalculation=force_weight_recalculation,
                n_bins=n_bins,
            )

        if "attribute_typology" not in hotspots_df.columns:
            raise ValueError(
                "hotspots_df does not contain an 'attribute_typology' column. "
                "Ensure it was produced by get_hotspots(what='demand_equity_combined')."
            )

        def _score_label(label: str) -> int:
            """
            Score a typology label 0 (best) → 4 (worst) based on combined severity.
            Works for any pairing of Demand / Deprivation / Access.
            """
            severity = {
                # Demand & Deprivation
                "High": 2,
                "Medium": 1,
                "Low": 0,
                # Access (inverted — Poor is worst)
                "Poor": 2,
                "Good": 0,
            }
            left, right = label.split(" / ")
            left_score = severity.get(left.split()[0], 1)  # fallback to 1 if unknown
            right_score = severity.get(right.split()[0], 1)
            return left_score + right_score

        def _mix(hex_a: str, hex_b: str, t: float = 0.5) -> str:
            """Blend two hex colours. t=0 → hex_a, t=1 → hex_b."""

            def to_rgb(h):
                h = h.lstrip("#")
                return [int(h[i : i + 2], 16) for i in (0, 2, 4)]

            a, b = to_rgb(hex_a), to_rgb(hex_b)
            mixed = [int(round(a[i] * (1 - t) + b[i] * t)) for i in range(3)]
            return "#%02x%02x%02x" % tuple(mixed)

        def _score_to_colour(
            score: int,
            priority_colour: str = "#d7191c",
            concerning_colour: str = "#fee08b",
            neutral_colour: str = "#bdbdbd",
            positive_colour: str = "#abd9e9",
        ) -> str:
            return {
                4: priority_colour,  # High+High, High+Poor
                3: concerning_colour,
                2: neutral_colour,  # "cancelling out" — one high, one low
                1: _mix(neutral_colour, positive_colour),  # e.g. Low+Medium
                0: positive_colour,  # Low+Good, Low+Low
            }[score]

        def get_typology_colour(
            label: str,
            n_bins: int = 2,
            priority_colour: str = "#d7191c",
            concerning_colour: str = "#fee08b",
            neutral_colour: str = "#bdbdbd",
            positive_colour: str = "#abd9e9",
        ) -> str:

            # ── 2x2 fallback (unchanged) ──────────────────────────────────────────────
            if n_bins == 2:
                left, right = label.split(" / ")
                y_map = {"High": 0, "Medium": 1, "Low": 2}
                x_map = {"Poor": 0, "High": 0, "Medium": 1, "Good": 2, "Low": 2}
                y_idx = y_map[left.split()[0]]
                x_idx = x_map[right.split()[0]]

                if y_idx == 0 and x_idx == 0:
                    return priority_colour
                if y_idx == 0 and x_idx == 2:
                    return (
                        concerning_colour if "Deprivation" in label else positive_colour
                    )
                if y_idx == 2 and x_idx == 0:
                    return concerning_colour
                return neutral_colour

            # ── 3x3 score-based categorical ───────────────────────────────────────────
            score = _score_label(label)
            return _score_to_colour(
                score,
                priority_colour=priority_colour,
                concerning_colour=concerning_colour,
                neutral_colour=neutral_colour,
                positive_colour=positive_colour,
            )

        # ── Colour assignment ──────────────────────────────────────────────────────────
        hotspots_df["_plot_colour"] = hotspots_df["attribute_typology"].map(
            lambda label: get_typology_colour(label, n_bins=n_bins)
        )

        typology_colours = {
            label: get_typology_colour(label, n_bins=n_bins)
            for label in hotspots_df["attribute_typology"].unique()
        }

        # ── Legend ordering ────────────────────────────────────────────────────────────

        hotspots_df["_plot_colour"] = hotspots_df["attribute_typology"].map(
            lambda label: get_typology_colour(label, n_bins=n_bins)
        )

        typology_colours = {
            label: get_typology_colour(label, n_bins=n_bins)
            for label in hotspots_df["attribute_typology"].unique()
        }

        # --- Configure Plotting Parameters based on Significance Availability ---
        has_significance = n_bins == 2 and significance_threshold is not None

        if has_significance:
            # Significance overlay: bold border for spatial clusters, quiet for the rest
            hotspots_df["_is_significant"] = hotspots_df["cluster_type"].isin(
                ["Hotspot", "Coldspot"]
            )
            hotspots_df["_edge_colour"] = hotspots_df["_is_significant"].map(
                {True: significant_edgecolor, False: non_significant_edgecolor}
            )
            hotspots_df["_edge_width"] = hotspots_df["_is_significant"].map(
                {True: significant_linewidth, False: non_significant_linewidth}
            )
            # Base colour mapping
            hotspots_df["_fill_colour"] = hotspots_df["attribute_typology"].map(
                typology_colours
            )
            # Apply dynamic opacity. Full opacity for significant, muted for non-significant.
            hotspots_df["_fill_rgba"] = hotspots_df.apply(
                lambda row: mcolors.to_rgba(
                    row["_fill_colour"], opacity if row["_is_significant"] else 0.15
                ),
                axis=1,
            )
        else:
            # Fallback uniform styling: No spatial context tracking (e.g. 3x3 matrices)
            hotspots_df["_is_significant"] = (
                True  # Standardizes downstream loops/styles
            )
            hotspots_df["_edge_colour"] = significant_edgecolor
            hotspots_df["_edge_width"] = non_significant_linewidth
            hotspots_df["_fill_colour"] = hotspots_df["attribute_typology"].map(
                typology_colours
            )
            hotspots_df["_fill_rgba"] = hotspots_df["_fill_colour"].apply(
                lambda c: mcolors.to_rgba(c, opacity)
            )

        # ---------------------------------------------------------------------
        # Interactive Map (Folium)
        # ---------------------------------------------------------------------
        if interactive:
            bounds = hotspots_df.to_crs(epsg=4326).total_bounds
            centre = [(bounds[1] + bounds[3]) / 2, (bounds[0] + bounds[2]) / 2]

            m = folium.Map(
                location=centre,
                tiles=tiles if show_basemap else None,
            )

            # Dynamically tailor tooltips to keep clean when columns don't exist
            tooltip_fields = [
                "attribute_typology",
                ctx._region_geometry_layer_common_col,
                "combined_score",
            ]
            tooltip_aliases = ["Attribute Typology", "Region", "Combined Score"]

            if has_significance:
                if "cluster_type" in hotspots_df.columns:
                    tooltip_fields.append("cluster_type")
                    tooltip_aliases.append("Spatial Cluster")
                if "p_value" in hotspots_df.columns:
                    tooltip_fields.append("p_value")
                    tooltip_aliases.append("p-value")

            for typology_label, colour in typology_colours.items():
                subset = hotspots_df[
                    hotspots_df["attribute_typology"] == typology_label
                ]
                if subset.empty:
                    continue

                fg = folium.FeatureGroup(name=typology_label, show=True)

                def style_fn(feature, c=colour):
                    is_significant = feature["properties"].get("_is_significant", True)

                    ew = (
                        significant_linewidth
                        if is_significant
                        else non_significant_linewidth
                    )
                    ec = (
                        significant_edgecolor
                        if is_significant
                        else non_significant_edgecolor
                    )
                    fill_op = opacity if is_significant else 0.15

                    return {
                        "fillColor": c,
                        "color": ec,
                        "weight": ew,
                        "fillOpacity": fill_op,
                    }

                folium.GeoJson(
                    data=subset,
                    style_function=style_fn,
                    tooltip=folium.GeoJsonTooltip(
                        fields=tooltip_fields,
                        aliases=tooltip_aliases,
                    ),
                ).add_to(fg)

                fg.add_to(m)

            folium.LayerControl(collapsed=False).add_to(m)
            m.fit_bounds([[bounds[1], bounds[0]], [bounds[3], bounds[2]]])

            return m

        # ---------------------------------------------------------------------
        # Static Map (Matplotlib)
        # ---------------------------------------------------------------------
        else:
            owns_figure = ax is None
            if ax is None:
                # If the user didn't provide an ax, create a fresh fig/ax with the custom size
                fig, ax = plt.subplots(
                    figsize=figsize or (10, 10), layout="constrained"
                )
            elif figsize is not None:
                # Warn if passed both, since figsize will be ignored
                warnings.warn("figsize is ignored when an explicit ax is provided.")

            # Plot layout layers
            for is_sig in [False, True]:
                subset = hotspots_df[hotspots_df["_is_significant"] == is_sig]
                if subset.empty:
                    continue

                subset.plot(
                    ax=ax,
                    color=subset["_fill_rgba"].tolist(),
                    edgecolor=subset["_edge_colour"].tolist(),
                    linewidth=(
                        significant_linewidth
                        if is_sig and has_significance
                        else non_significant_linewidth
                    ),
                    **kwargs,
                )

            if show_basemap:
                try:
                    cx.add_basemap(ax, crs=hotspots_df.crs.to_string(), timeout=30)
                except RequestException as e:
                    warnings.warn(
                        f"Unable to download background map tiles ({type(e).__name__}). "
                        "Continuing without a basemap.",
                        stacklevel=2,
                    )

            if not show_axis:
                ax.axis("off")

            # Build Legends
            # Sort labels by severity score, highest first
            typology_handles = [
                Patch(facecolor=colour, edgecolor="#555555", linewidth=0.5, label=label)
                for label, colour in sorted(
                    typology_colours.items(),
                    key=lambda item: _score_label(item[0]),
                    reverse=True,
                )
            ]

            # Build legend depending on the positioning
            if legend_loc == "outside" and not owns_figure:
                if legend_bbox_to_anchor:
                    typology_bbox = legend_bbox_to_anchor
                else:
                    typology_bbox = (1.02, 1.0)

                typology_legend = ax.legend(
                    handles=typology_handles,
                    title="Attribute Typology",
                    loc="upper left",
                    bbox_to_anchor=typology_bbox,
                    borderaxespad=0,
                    framealpha=0.9,
                )

                ax.add_artist(typology_legend)

                # Render second legend only if significance overlay exists
                if has_significance:
                    significance_handles = [
                        Patch(
                            facecolor="white",
                            edgecolor=significant_edgecolor,
                            linewidth=significant_linewidth,
                            label="Significant spatial cluster",
                        ),
                        Patch(
                            facecolor="white",
                            edgecolor=non_significant_edgecolor,
                            linewidth=non_significant_linewidth,
                            label="Not significant",
                        ),
                    ]

                    ax.get_figure().legend(
                        handles=significance_handles,
                        title="Spatial Significance",
                        loc="upper left",
                        bbox_to_anchor=(0.80, 0.55),
                        borderaxespad=0,
                        framealpha=0.9,
                    )

            elif legend_loc == "outside" and owns_figure:
                # Shrink the axes to leave room on the right, AFTER basemap (which may
                # lock aspect ratio). set_position works in figure-fraction space and
                # isn't affected by equal-aspect constraints the way tight_layout is.
                pos = ax.get_position()
                ax.set_position([pos.x0, pos.y0, pos.width * 0.78, pos.height])

                typology_legend = ax.get_figure().legend(
                    handles=typology_handles,
                    title="Attribute Typology",
                    loc="upper left",
                    bbox_to_anchor=legend_bbox_to_anchor
                    if legend_bbox_to_anchor is not None
                    else (0.80, 0.95),
                    borderaxespad=0,
                    framealpha=0.9,
                )

                # Render second legend only if significance overlay exists
                if has_significance:
                    significance_handles = [
                        Patch(
                            facecolor="white",
                            edgecolor=significant_edgecolor,
                            linewidth=significant_linewidth,
                            label="Significant spatial cluster",
                        ),
                        Patch(
                            facecolor="white",
                            edgecolor=non_significant_edgecolor,
                            linewidth=non_significant_linewidth,
                            label="Not significant",
                        ),
                    ]

                    ax.get_figure().legend(
                        handles=significance_handles,
                        title="Spatial Significance",
                        loc="upper left",
                        bbox_to_anchor=(0.80, 0.55),
                        borderaxespad=0,
                        framealpha=0.9,
                    )

            # if legend is not set to be inside
            else:
                typology_bbox = legend_bbox_to_anchor

                typology_legend = ax.legend(
                    handles=typology_handles,
                    title="Attribute Typology",
                    loc=legend_loc,
                    bbox_to_anchor=typology_bbox,
                    framealpha=0.9,
                )

                ax.add_artist(typology_legend)

                # Render second legend only if significance overlay exists
                if has_significance:
                    significance_handles = [
                        Patch(
                            facecolor="white",
                            edgecolor=significant_edgecolor,
                            linewidth=significant_linewidth,
                            label="Significant spatial cluster",
                        ),
                        Patch(
                            facecolor="white",
                            edgecolor=non_significant_edgecolor,
                            linewidth=non_significant_linewidth,
                            label="Not significant",
                        ),
                    ]
                    ax.legend(
                        handles=significance_handles,
                        title="Spatial Significance",
                        loc="lower right"
                        if legend_loc != "lower right"
                        else "lower left",
                        framealpha=0.9,
                    )

            _TYPOLOGY_TITLES = {
                "demand_equity": ("Demand / Deprivation", "demand & deprivation"),
                "travel_time": ("Travel Time Access", "travel time"),
                "travel_demand": ("Demand / Access", "demand & access"),
                "travel_equity": ("Deprivation / Access", "deprivation & access"),
            }

            title_label, method_label = _TYPOLOGY_TITLES.get(
                what, (what.replace("_", " ").title(), what)
            )

            # Clean subtitle note depending on whether borders carry significance meaning
            border_note = (
                "bold border = significant spatial cluster, "
                if has_significance
                else ""
            )
            ax.set_title(
                f"{title_label} Typology\n"
                f"({border_note}combination: {method_label}, method: {combination_method})",
                fontsize=10,
            )

            return ax
