import numpy as np
from itertools import combinations
from functools import wraps
import inspect
from pandas.api.types import is_numeric_dtype
import pandas as pd
import geopandas as gpd
from pathlib import Path

# Todo - update these as generated by Gemini with only minimal revisions so far
SOLVER_DEFINITIONS = {
    "p_median": {
        "name": "P-Median (Average Distance Minimizer)",
        "goal": "Minimize the total travel distance for the entire population.",
        "healthcare_context": "Best for general primary care where you want the 'average' patient to have the shortest trip possible.",
        "trade_off": "Can leave remote or rural patients with very long travel times in favor of urban density.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "mclp": {
        "name": "Maximal Coverage Location Problem (MCLP)",
        "goal": "Maximize the number of people within a specific time/distance 'threshold' (e.g., 15 minutes).",
        "healthcare_context": "Best for emergency services (Ambulance/ER) where getting there within a 'Golden Hour' is more important than the average trip time.",
        "trade_off": "Does not care how far away people are once they are outside the threshold.",
        "status": "Planned",
        "academic_ref": "Church & ReVelle (1974)",
    },
    "lscp": {
        "name": "Location Set Covering Location Problem (LSCP)",
        "goal": "Find the minimum number of facilities needed to cover *everyone* within a certain distance.",
        "healthcare_context": "Best for universal mandates (e.g., ensuring every citizen is within 20 miles of a pharmacy).",
        "trade_off": "Can be very expensive as it forces clinics into sparsely populated areas to reach the final 1%.",
        "status": "Planned",
        "academic_ref": "Toregas et al. (1971)",
    },
    "lscp-b": {
        "name": "LSCP-B (Backup Coverage Model)",
        "goal": "Minimize the number of facilities needed to ensure everyone is covered by AT LEAST TWO locations.",
        "healthcare_context": "Critical for high-reliability services like Maternity units or Stroke centers where 'System Busy' is a life-threatening risk.",
        "trade_off": "Requires significantly more resources (budget/staff) than standard coverage to achieve the same geographic footprint.",
        "status": "Planned",
        "academic_ref": "Hogan & ReVelle (1986), Church & Murray (2018)",
    },
    "p_center": {
        "name": "P-Center (The Fair-Maximum Model)",
        "goal": "Minimize the maximum travel time for the furthest patient.",
        "healthcare_context": "Best for ensuring universal access in rural regions; 'No one left behind'.",
        "trade_off": "Can lead to higher average travel times for the majority population.",
        "status": "Planned",
        "academic_ref": "Suzuki & Drezner (1996)",
    },
}


def _check_crs_match(gdf_1, gdf_2):
    """
    Check that the coordinate reference system of two geodataframes is the same and warn if it is not
    """
    assert gdf_1.crs == gdf_2.crs, f"CRS Mismatch. {gdf_1.crs} vs {gdf_2.crs}."


def _guess_crs(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    sample_size: int = 1000,
    verbose: bool = True,
):
    """
    Guess CRS (EPSG:4326 or EPSG:27700) from coordinate columns and return a GeoDataFrame.

    Parameters
    ----------
    df : pd.DataFrame
    x_col : str
        Column containing longitude or easting
    y_col : str
        Column containing latitude or northing
    sample_size : int
        Number of rows to sample for inference
    verbose : bool
        Whether to print reasoning

    Returns
    -------
    gpd.GeoDataFrame
        GeoDataFrame with guessed CRS

    Raises
    ------
    ValueError
        If CRS cannot be confidently determined
    """

    # Drop NA and sample
    sample = df[[x_col, y_col]].dropna().head(sample_size)

    x = sample[x_col]
    y = sample[y_col]

    # Heuristic checks
    is_latlon = x.between(-180, 180).all() and y.between(-90, 90).all()

    is_bng = x.between(0, 700000).all() and y.between(0, 1300000).all()

    # Optional tighter UK bounds (improves confidence)
    is_bng_tight = (
        x.between(0, 700000).all()
        and y.between(0, 1300000).all()
        and x.mean() > 100000
        and x.mean() < 700000
        and y.mean() > 0
        and y.mean() < 1300000
    )

    if is_latlon and not is_bng:
        crs = "EPSG:4326"
        reason = "Values fall within longitude/latitude bounds"

    elif is_bng_tight and not is_latlon:
        crs = "EPSG:27700"
        reason = "Values fall within British National Grid bounds"

    elif is_bng and not is_latlon:
        crs = "EPSG:27700"
        reason = "Values look like projected coordinates (BNG range)"

    else:
        raise ValueError(
            "Unable to confidently determine CRS. Please specify manually."
        )

    if verbose:
        print(f"Guessed CRS: {crs} ({reason})")


def _validate_columns(
    df,
    col_names,
    numeric_col_names=None,
    msg_template=None,
    context=None,
):
    if numeric_col_names is None:
        numeric_col_names = []

    # --- 1. Check for Missing Columns ---
    missing = [c for c in col_names if c not in df.columns]

    if missing:
        if msg_template:
            error_msg = msg_template.format(missing=missing, available=list(df.columns))
        else:
            context_str = f" in {context}" if context else ""
            error_msg = f"Missing columns{context_str}: {missing}"
        raise ValueError(error_msg)

    # --- 2. Check for Numeric Data Types ---
    non_numeric = [
        col
        for col in numeric_col_names
        if col in df.columns and not is_numeric_dtype(df[col])
    ]

    if non_numeric:
        raise TypeError(
            f"Data Type Error: The following columns must contain numbers (integers or floats), "
            f"but they contain other types (like strings): {non_numeric}. "
            "Hint: Try using pd.to_numeric() on these columns before passing them in."
        )


def _generate_all_combinations(n_facilities: int, p: int) -> list:
    """
    Generate all possible permutations of a list without replacement.

    n_facilities: int
        The total number of facilities that exist

    p: int
        The number of candidate solutions
    """

    # Code modified from https://github.com/health-data-science-OR/healthcare-logistics
    # Credit for original code to Dr Tom Monks
    # Licence reproduced below in line with reuse conditions
    # MIT License
    #
    # Copyright (c) 2020 health-data-science-OR
    #
    # Permission is hereby granted, free of charge, to any person obtaining a copy
    # of this software and associated documentation files (the "Software"), to deal
    # in the Software without restriction, including without limitation the rights
    # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    # copies of the Software, and to permit persons to whom the Software is
    # furnished to do so, subject to the following conditions:
    #
    # The above copyright notice and this permission notice shall be included in all
    # copies or substantial portions of the Software.
    #
    # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    # SOFTWARE.

    facility = np.arange(n_facilities, dtype=int)
    return [np.array(a) for a in combinations(facility, p)]


def _load_spatial_or_tabular_data(data_input):
    """
    Takes a file path or a DataFrame and returns the loaded DataFrame
    alongside a string indicating its spatial type.

    Returns:
        tuple: (DataFrame/GeoDataFrame, str indicating 'pandas' or 'geopandas')
    """
    # 1. Is it already a GeoDataFrame?
    if isinstance(data_input, gpd.GeoDataFrame):
        return data_input, "geopandas"

    # 2. Is it already a standard pandas DataFrame?
    elif isinstance(data_input, pd.DataFrame):
        return data_input, "pandas"

    # 3. Is it a file path (string or Path object)?
    elif isinstance(data_input, (str, Path)):
        path = Path(data_input)

        if not path.exists():
            raise FileNotFoundError(f"Oops! I couldn't find a file at: {path}")

        ext = path.suffix.lower()

        # Define expected extensions
        pandas_exts = [".csv", ".parquet", ".xlsx"]
        geopandas_exts = [".shp", ".geojson", ".gpkg"]

        if ext in pandas_exts:
            if ext == ".csv":
                df = pd.read_csv(path)
            elif ext == ".parquet":
                df = pd.read_parquet(path)
            elif ext == ".xlsx":
                df = pd.read_excel(path)
            return df, "pandas"

        elif ext in geopandas_exts:
            df = gpd.read_file(path)
            return df, "geopandas"

        else:
            raise ValueError(
                f"Unsupported file extension '{ext}'. "
                f"Please provide a file with one of these extensions: {pandas_exts + geopandas_exts}"
            )

    # 4. If it's none of the above, raise an error
    else:
        raise TypeError(
            "Invalid input. Please provide a pandas DataFrame, a geopandas GeoDataFrame, "
            "or a valid file path string."
        )
