import numpy as np
from dataclasses import replace
from itertools import combinations
from pandas.api.types import is_numeric_dtype
import pandas as pd
import geopandas
from pathlib import Path
from urllib.parse import urlparse
import requests
from io import BytesIO
import textwrap
from warnings import warn
import matplotlib.pyplot as plt
import seaborn as sns

from lokigi.multiobjective import Metric

PANDAS_EXTS = [".csv", ".parquet", ".xlsx", ".xls"]
GEOPANDAS_EXTS = [".shp", ".geojson", ".gpkg"]

SUPPORTED_OBJECTIVES = [
    "p_median",
    "hybrid_p_median",
    "p_center",
    "simple_p_median",
    "hybrid_simple_p_median",
    "mclp",
    "custom",
]

# Ranking columns with a `_for_ranking` twin computed by
# `EvaluatedCombination._compute_travel_metrics`. These are exactly the
# metrics that average or maximise over *reachable* rows only, so ranking on
# them unsubstituted silently rewards a combination for stranding demand --
# see `_get_ranking_by_objective` and `solve()`'s `unreachable_cost`.
_FOR_RANKING_BASE_COLUMNS = ["weighted_average", "unweighted_average", "max"]

PLANNED_OBJECTIVES = [
    "lscp",
    "lscp_b",
]

# Todo - update these as generated by Gemini with only minimal revisions so far
SOLVER_DEFINITIONS = {
    "simple_p_median": {
        "name": "P-Median (Average Distance Minimizer)",
        "goal": "Minimize the total travel distance or time.",
        "healthcare_context": "Best for situations like siting a series of storage hubs efficiently across a region where demand/volume doesn't matter.",
        "trade_off": "Can leave remote or rural patients with very long travel times in favor of urban density.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "p_median": {
        "name": "P-Median (Average Weighted Distance Minimizer)",
        "goal": "Minimize the total travel distance or time for the entire population, weighting the travel times by a metric such as demand per region.",
        "healthcare_context": "Best for general primary care where you want the 'average' patient to have the shortest trip possible.",
        "trade_off": "Can leave remote or rural patients with very long travel times in favor of urban density.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "hybrid_simple_p_median": {
        "name": "Hybrid Simple P-Median (The Safety Net Model)",
        "goal": "Minimize the total travel distance or time, weighting the travel times by a metric such as demand per region, while guaranteeing a maximum 'cutoff' time for every patient.",
        "healthcare_context": "Makes the system efficient while preventing major 'postcode lotteries' where some patients travel a very long way.",
        "trade_off": "Hard cut-off point could see some good solutions that nearly meet the cutoff being discarded.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "hybrid_p_median": {
        "name": "Hybrid P-Median (The Safety Net Model)",
        "goal": "Minimize average travel distance or time while guaranteeing a maximum 'cutoff' time for every patient.",
        "healthcare_context": "Makes the system efficient while preventing major 'postcode lotteries' where some patients travel a very long way.",
        "trade_off": "Hard cut-off point could see some good solutions that nearly meet the cutoff being discarded.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "p_center": {
        "name": "P-Center (The Fair-Maximum Model)",
        "goal": "Minimize the maximum travel distance or time for the furthest patient.",
        "healthcare_context": "Best for ensuring universal access in rural regions; 'No one left behind'.",
        "trade_off": "Can lead to higher average travel distances or times for the majority population.",
        "status": "Supported",
        "academic_ref": "Suzuki & Drezner (1996)",
    },
    "mclp": {
        "name": "Maximal Coverage Location Problem (MCLP)",
        "goal": "Maximize the number of people within a specific time/distance 'threshold' (e.g., 15 minutes).",
        "healthcare_context": "Best for emergency services (Ambulance/ER) where getting there within a 'Golden Hour' is more important than the average trip time.",
        "trade_off": "Does not care how far away people are once they are outside the threshold.",
        "status": "Supported",
        "academic_ref": "Church & ReVelle (1974)",
    },
    "lscp": {
        "name": "Location Set Covering Location Problem (LSCP)",
        "goal": "Find the minimum number of facilities needed to cover *everyone* within a certain distance.",
        "healthcare_context": "Best for universal mandates (e.g., ensuring every citizen is within 20 miles of a pharmacy).",
        "trade_off": "Can be very expensive as it forces clinics into sparsely populated areas to reach the final 1%.",
        "status": "Planned",
        "academic_ref": "Toregas et al. (1971)",
    },
    "lscp-b": {
        "name": "LSCP-B (Backup Coverage Model)",
        "goal": "Minimize the number of facilities needed to ensure everyone is covered by AT LEAST TWO locations.",
        "healthcare_context": "Critical for high-reliability services like Maternity units or Stroke centers where 'System Busy' is a life-threatening risk.",
        "trade_off": "Requires significantly more resources (budget/staff) than standard coverage to achieve the same geographic footprint.",
        "status": "Planned",
        "academic_ref": "Hogan & ReVelle (1986), Church & Murray (2018)",
    },
    "custom": {
        "name": "Custom (caller-defined ranking metric)",
        "goal": "Rank solutions on whichever metric solve() already computes that you name via rank_on=, with no model-specific constraints applied.",
        "healthcare_context": "Use when the measure you actually care about isn't one of the named models above -- e.g. searching directly on inter_tertile_ratio (equity), or on the number of people left beyond a threshold. Pass rank_on= to a named objective instead if you also want that model's constraints (e.g. hybrid_p_median's max_value_cutoff).",
        "trade_off": "Applies no feasibility constraints of its own, so nothing bounds the metrics you did not rank on -- check them in the returned solutions rather than assuming they are reasonable.",
        "status": "Supported",
        "academic_ref": "N/A -- not a named model from the location-allocation literature",
    },
}


ALGORITHM_DEFINITIONS = {
    "brute_force": {
        "name": "Brute Force (Exact Search)",
        "mechanism": "Checks every single possible combination of sites mathematically available.",
        "trade_off": "Computationally explosive. Adding just a few more sites can increase solve time from seconds to years. Use only for very small projects (e.g., picking 3 sites out of 10). Guaranteed to find the 'Global Optimum'.",
        "status": "Supported",
    },
    "random_restarts": {
        "name": "Random Restarts",
        "mechanism": "Runs a local search multiple times, each time starting from a completely different random set of sites.",
        "healthcare_context": "Provides the 'Portfolio of Options' managers need. It explores the map more widely to find diverse 'good' solutions.",
        "trade_off": "Diminishing returns; eventually, you're just using time and computational resources to find the same few solutions again.",
        "status": "Planned",
    },
    "greedy_add": {
        "name": "Greedy Addition",
        "mechanism": "Starts with zero sites and adds the single best location one-by-one until the target is reached.",
        "trade_off": "Short-sighted; it never re-evaluates early choices, which might lead to a sub-optimal final network.",
        "status": "Planned",
    },
    "local_search_swap": {
        "name": "Local Search (The Swap Heuristic)",
        "mechanism": "Starts with a solution and tries swapping one active site for an inactive one to see if it improves the score. Also known as 'Teitz-Bart' or the 'hill-climbing' algorithm.",
        "trade_off": "Prone to getting stuck in 'Local Optima'—it finds a good solution but might miss a radically different, better one.",
        "status": "Planned",
    },
    "grasp": {
        "name": "GRASP (Greedy Randomized Adaptive Search Procedure)",
        "mechanism": "A mix of greedy and random: it picks from a 'restricted candidate list' of the top few best moves at each step. It finds solutions that are high-performing but non-obvious, avoiding the 'predictable' greedy paths.",
        "trade_off": "Requires tuning the 'greediness' parameter. If too random, it’s aimless; if too greedy, it lacks diversity.",
        "status": "Planned",
    },
}


def _check_crs_match(gdf_1, gdf_2, strict=False):
    """
    Check that the coordinate reference system of two geodataframes is the same and warn if it is not
    """
    try:
        if strict:
            assert gdf_1.crs == gdf_2.crs, f"CRS Mismatch. {gdf_1.crs} vs {gdf_2.crs}."
        else:
            return gdf_1.crs == gdf_2.crs
    except AttributeError:
        warn(f"Could not check crs. CRS 1: {gdf_1.crs}. CRS 2: {gdf_2.crs}")


def _check_crs_match_pref(gdf, pref, strict=False):
    if strict:
        assert gdf.crs.to_string() == pref, (
            f"CRS Mismatch. {gdf.crs.to_string()} vs {pref}."
        )
    else:
        return gdf.crs.to_string() == pref


def _guess_crs(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    sample_size: int = 1000,
    verbose: bool = True,
):
    """
    Guess CRS (EPSG:4326 or EPSG:27700) from coordinate columns and return a GeoDataFrame.

    Parameters
    ----------
    df : pd.DataFrame
    x_col : str
        Column containing longitude or easting
    y_col : str
        Column containing latitude or northing
    sample_size : int
        Number of rows to sample for inference
    verbose : bool
        Whether to print reasoning

    Returns
    -------
    geopandas.GeoDataFrame
        GeoDataFrame with guessed CRS

    Raises
    ------
    ValueError
        If CRS cannot be confidently determined
    """

    # Drop NA and sample
    sample = df[[x_col, y_col]].dropna().head(sample_size)

    x = sample[x_col]
    y = sample[y_col]

    # Heuristic checks
    is_latlon = x.between(-180, 180).all() and y.between(-90, 90).all()

    is_bng = x.between(0, 700000).all() and y.between(0, 1300000).all()

    # Optional tighter UK bounds (improves confidence)
    is_bng_tight = (
        x.between(0, 700000).all()
        and y.between(0, 1300000).all()
        and x.mean() > 100000
        and x.mean() < 700000
        and y.mean() > 0
        and y.mean() < 1300000
    )

    if is_latlon and not is_bng:
        crs = "EPSG:4326"
        reason = "Values fall within longitude/latitude bounds"

    elif is_bng_tight and not is_latlon:
        crs = "EPSG:27700"
        reason = "Values fall within British National Grid bounds"

    elif is_bng and not is_latlon:
        crs = "EPSG:27700"
        reason = "Values look like projected coordinates (BNG range)"

    else:
        raise ValueError(
            "Unable to confidently determine CRS. Please specify manually."
        )

    if verbose:
        print(f"Guessed CRS: {crs} ({reason})")

    return crs


def _convert_crs(df, target_crs):
    return df.to_crs(target_crs)


def _validate_columns(
    df,
    col_names,
    numeric_col_names=None,
    msg_template=None,
    context=None,
):
    if not isinstance(df, (pd.DataFrame, geopandas.GeoDataFrame)):
        raise TypeError(
            f"Passed a {type(df)} where a Pandas or Geopandas dataframe was expected."
        )

    if numeric_col_names is None:
        numeric_col_names = []

    # --- 1. Check for Missing Columns ---
    missing = [c for c in col_names if c not in df.columns]

    if missing:
        if msg_template:
            error_msg = msg_template.format(missing=missing, available=list(df.columns))
        else:
            context_str = f" in {context}" if context else ""
            error_msg = (
                f"Missing columns{context_str}: {missing}. Found columns: {df.columns}"
            )
        raise ValueError(error_msg)

    # --- 2. Check for Numeric Data Types ---
    non_numeric = [
        col
        for col in numeric_col_names
        if col in df.columns and not is_numeric_dtype(df[col])
    ]

    if non_numeric:
        raise TypeError(
            f"Data Type Error: The following columns must contain numbers (integers or floats), "
            f"but they contain other types (like strings): {non_numeric}. "
            "Hint: Try using pd.to_numeric() on these columns before passing them in."
        )


def _get_required_site_indices(site_problem) -> list:
    """
    Integer positions of candidate sites flagged as required via
    `add_sites(required_sites_col=...)`, or an empty list if no required
    sites column is configured.

    Flag values are matched case-insensitively against a set of sensible
    "truthy" markers, so the column may hold booleans, integers, or messy
    strings ("Y", " true ", 1, ...).

    Tolerates a `site_problem` that doesn't define
    `_candidate_sites_required_sites_col` at all (e.g. a minimal stub used
    in tests to isolate a single metric), treating it the same as "no
    required sites configured" rather than raising.
    """
    if site_problem is None or getattr(
        site_problem, "_candidate_sites_required_sites_col", None
    ) is None:
        return []

    truthy_values = {"y", "yes", "true", "t", "required", "1"}

    col_data = (
        site_problem.candidate_sites[site_problem._candidate_sites_required_sites_col]
        .astype(str)
        .str.lower()
        .str.strip()
    )

    is_required = col_data.isin(truthy_values)

    return [int(i) for i in np.where(is_required)[0]]


def _generate_all_combinations(
    n_facilities: int, p: int, site_problem=None, force_include_indices=None
) -> list:
    """
    Generate all possible permutations of a list without replacement.

    n_facilities: int
        The total number of facilities that exist

    p: int
        The number of candidate solutions
    """

    # Code modified from https://github.com/health-data-science-OR/healthcare-logistics
    # Credit for original code to Dr Tom Monks
    # Licence reproduced below in line with reuse conditions
    # MIT License
    #
    # Copyright (c) 2020 health-data-science-OR
    #
    # Permission is hereby granted, free of charge, to any person obtaining a copy
    # of this software and associated documentation files (the "Software"), to deal
    # in the Software without restriction, including without limitation the rights
    # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    # copies of the Software, and to permit persons to whom the Software is
    # furnished to do so, subject to the following conditions:
    #
    # The above copyright notice and this permission notice shall be included in all
    # copies or substantial portions of the Software.
    #
    # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    # SOFTWARE.

    facility = np.arange(n_facilities, dtype=int)
    result = [np.array(a) for a in combinations(facility, p)]

    # if site_problem is not None and force_include_indices is not None:
    #     raise ValueError(
    #         "Dev error: please provide only one of site_problem or"
    #         "force_include_indices to _generate_all_combinations()"
    #     )

    if site_problem is not None:
        required_indices = _get_required_site_indices(site_problem)
        if required_indices:
            # Convert required indices to a set for O(1) lookups
            required_set = set(required_indices)

            # Filter the combinations to only keep those containing ALL required sites
            result = [a for a in result if required_set.issubset(a)]

    if force_include_indices is not None:
        # Convert required indices to a set for O(1) lookups
        required_set = set(force_include_indices)

        # Filter the combinations to only keep those containing ALL required sites
        result = [a for a in result if required_set.issubset(a)]

    return result


def _try_drop(df, drop_cols):
    if drop_cols:
        missing_cols = [col for col in drop_cols if col not in df.columns]

        if missing_cols:
            raise ValueError(
                f"The following columns were not found in the GeoDataFrame: {missing_cols}"
            )

        try:
            df = df.drop(columns=drop_cols)
        except Exception as e:
            raise ValueError(
                f"Failed to drop columns {drop_cols} from GeoDataFrame."
            ) from e

    return df


def _load_spatial_or_tabular_data(data_input, skip_cols=None):
    """
    Takes a file path, URL, file-like object, or a DataFrame and returns the loaded DataFrame
    alongside a string indicating its spatial type. Supports GitHub raw content conversion.
    """

    # 1. Handle existing DataFrames
    if isinstance(data_input, geopandas.GeoDataFrame):
        return _try_drop(data_input, skip_cols), "geopandas"
    if isinstance(data_input, pd.DataFrame):
        return _try_drop(data_input, skip_cols), "pandas"

    content = data_input
    ext = ""

    # 2. Handle Strings (URLs or Local Paths)
    if isinstance(data_input, (str, Path)):
        data_str = str(data_input)
        parsed = urlparse(data_str)

        if parsed.scheme in ("http", "https"):
            # Normalize GitHub URLs to raw content
            if "github.com" in data_str and "/blob/" in data_str:
                data_str = data_str.replace(
                    "github.com", "raw.githubusercontent.com"
                ).replace("/blob/", "/")

            # Fetch content
            response = requests.get(data_str, allow_redirects=True)
            response.raise_for_status()

            content = BytesIO(response.content)
            # Get extension from the actual URL path, not the redirecting one
            ext = Path(urlparse(data_str).path).suffix.lower()
        else:
            path = Path(data_input)
            if not path.exists():
                raise FileNotFoundError(f"I couldn't find a file at: {path}")
            content = path
            ext = path.suffix.lower()

    # 3. Handle File-like objects
    elif hasattr(data_input, "read"):
        content = data_input
        name = getattr(data_input, "name", "")
        ext = Path(name).suffix.lower()

    else:
        raise TypeError(
            "Invalid input type. Provide a DataFrame, URL, path, or file-like object."
        )

    # --- Router: Read based on extension ---

    # Priority 1: GeoPandas
    if ext in GEOPANDAS_EXTS or ext == ".json":
        try:
            # We use content for GeoJSON/GPKG, etc.
            # Note: For .zip (Shapefiles), GeoPandas usually needs a path or specific handle
            df = geopandas.read_file(content)
            return _try_drop(df, skip_cols), "geopandas"
        except Exception as e:
            # If it failed but it's a JSON-like extension, it might just be a pandas-style JSON
            if ext not in {".geojson", ".shp"}:
                pass
            else:
                raise e

    # Priority 2: Pandas
    if ext in PANDAS_EXTS:
        if ext == ".csv":
            df = pd.read_csv(content)
        if ext == ".parquet":
            df = pd.read_parquet(content)
        if ext in [".xlsx", ".xls"]:
            df = pd.read_excel(content)

        return _try_drop(df, skip_cols), "pandas"

    # Final Fallback: Try GeoPandas anyway if extension is ambiguous
    try:
        df = geopandas.read_file(content)
        return _try_drop(df, skip_cols), "geopandas"
    except:
        raise ValueError(f"Could not parse data with extension '{ext}'.")


def _safe_evaluate(text_string, solution):
    try:
        return eval(f"f{repr(text_string)}", {}, {"solution": solution})
    except Exception:
        # fallback: treat as literal string
        return text_string


def _get_ranking_by_objective(objective, unreachable_cost=None):
    """
    The `solution_df` column search/pruning ranks combinations on, for a
    given objective.

    `unreachable_cost` resolves to the `_for_ranking` variant of that
    column (`weighted_average_for_ranking`, etc.) whenever it is not
    `None` -- computed by `EvaluatedCombination._compute_travel_metrics`
    with every unreachable (NaN) travel cost substituted by
    `unreachable_cost`, so a combination that stranded demand is never
    silently rewarded by those rows simply dropping out of a reachable-
    only average. 'mclp' never needs this: its coverage-proportion ranking
    already treats an unreachable pair as "not covered" (correctly bad),
    with no equivalent silent-reward failure mode, so it is left on its
    plain column regardless of `unreachable_cost`.
    """
    if objective in ["p_median", "hybrid_p_median"]:
        base = "weighted_average"
    elif objective in ["simple_p_median", "hybrid_simple_p_median"]:
        base = "unweighted_average"
    elif objective in ["p_center"]:
        base = "max"
    elif objective in ["mclp"]:
        # Demand-weighted since v0.7.0, matching the textbook Maximal Covering
        # Location Problem. The column name is unchanged; its meaning is not.
        return "proportion_within_coverage_threshold"
    else:
        # Includes 'custom', which has no default column of its own -- it
        # requires rank_on, and solve() rejects it without one.
        return None

    return f"{base}_for_ranking" if unreachable_cost is not None else base


def _resolve_ranking_metric(objective, rank_on=None, unreachable_cost=None):
    """
    Resolve what `solve()` should actually rank and prune on, as a single
    `Metric`.

    Direction used to be decided independently in four places -- the
    brute-force heap, the greedy per-step sort, GRASP's `is_minimization`,
    and the final cross-strategy sort -- each spelled `objective == "mclp"`.
    That works only while every objective's ranking column is either plainly
    higher- or plainly lower-is-better, which `rank_on` breaks: an
    inter-tertile ratio is best at 1.0, with both >1 and <1 worse. So all
    four now read the `Metric` this returns, and use `Metric.normalise()`
    to get a value where lower is always better.

    Parameters
    ----------
    objective : str
        The objective passed to `solve()`. Supplies the default ranking
        column (and its direction) when `rank_on` is None.
    rank_on : str or Metric, optional
        Overrides the objective's default ranking column. A bare string
        takes its direction from `_is_maximise_metric`; pass a `Metric` to
        state the direction explicitly, which is the only way to express
        `closest_to_target`.
    unreachable_cost : float, optional
        As passed to `solve()`. See the `_for_ranking` note below.

    Returns
    -------
    tuple[Metric, str or None]
        The resolved metric, and a warning message (or None). The caller
        emits the warning so it points at the user's `solve()` call rather
        than at this helper.

    Notes
    -----
    When `unreachable_cost` is set, a ranking column in
    `_FOR_RANKING_BASE_COLUMNS` is upgraded to its `_for_ranking` twin --
    the same substitution `_get_ranking_by_objective` already makes for the
    objective's default column. Honouring a literal `rank_on="max"` here
    would rank on the reachable-only figure and so reintroduce exactly the
    silent-reward bug `unreachable_cost` exists to prevent. It's a warning
    rather than an error because the intent is unambiguous and we can do
    the right thing; it's not silent because the column that ends up in
    `solution_rank` is then not the one that was asked for.
    """
    if rank_on is None:
        column = _get_ranking_by_objective(
            objective=objective, unreachable_cost=unreachable_cost
        )
        if column is None:
            return None, None
        direction = "higher_better" if objective == "mclp" else "lower_better"
        return Metric(column=column, direction=direction), None

    if isinstance(rank_on, str):
        metric = Metric(
            column=rank_on,
            direction="higher_better" if _is_maximise_metric(rank_on) else "lower_better",
        )
    elif isinstance(rank_on, Metric):
        metric = replace(rank_on)
    else:
        raise TypeError(
            f"Expected 'rank_on' to be a column name (str) or a "
            f"lokigi.multiobjective.Metric, got {type(rank_on).__name__}."
        )

    warning = None
    if unreachable_cost is not None and metric.column in _FOR_RANKING_BASE_COLUMNS:
        upgraded = f"{metric.column}_for_ranking"
        warning = (
            f"rank_on='{metric.column}' was upgraded to '{upgraded}' because "
            f"unreachable_cost={unreachable_cost} is set. '{metric.column}' "
            "averages over reachable demand only, so ranking on it would "
            "reward a solution for leaving demand unreachable (those rows "
            "drop out of the average instead of counting against it). Pass "
            f"rank_on='{upgraded}' explicitly to silence this, or drop "
            "unreachable_cost to rank on reachable demand only."
        )
        metric = replace(metric, column=upgraded)

    return metric, warning


def _population_impact_metrics(
    current, baseline, demand=None, meaningful_change_threshold=0.0
):
    """
    Per-region diff of `current` vs `baseline`, classified into
    improved/worsened/unchanged and summarised by region count and (if
    `demand` is given) demand-weighted people count.

    Shared by `SolutionComparator.population_impact_summary()` (v1) and
    `solve(baseline=...)` (v2) so the two paths cannot silently drift apart
    on the same underlying arithmetic.

    Parameters
    ----------
    current, baseline : array-like of float
        Per-region travel cost, aligned to the same region order (the
        caller is responsible for alignment -- e.g. by demand-location ID,
        never by position/index alone).
    demand : array-like of float, optional
        Per-region demand weight, aligned to the same region order. `None`
        when no demand data is registered on the problem -- `demand_*`,
        `proportion_demand_*`, `total_demand` and the two weighted-mean
        columns are then `NaN`, and only the `regions_*` counts and the
        (unweighted-mean) improvement/worsening magnitudes are populated.
    meaningful_change_threshold : float, default 0.0
        A region's cost must have moved by strictly more than
        `max(meaningful_change_threshold, 1e-9)` to count as improved or
        worsened; anything else (including exactly
        `meaningful_change_threshold`) is `unchanged`. The `1e-9` floor
        absorbs floating-point noise at the default threshold of 0.0.

    Returns
    -------
    dict
        `regions_improved`/`regions_worsened`/`regions_unchanged` (counts);
        `demand_improved`/`demand_worsened`/`demand_unchanged` (`NaN` if
        `demand` is None); `proportion_demand_improved`/
        `proportion_demand_worsened` (share of `total_demand`, `NaN` if
        `demand` is None or its total is <= 0); `total_demand` (`NaN` if
        `demand` is None); `mean_reduction_among_improved`/
        `mean_increase_among_worsened` (demand-weighted mean if `demand`
        is given, else a plain mean; positive magnitudes; `NaN` if the
        bucket is empty, or if `demand` is given but every region in the
        bucket has zero/NaN demand); `max_reduction`/`max_increase`
        (largest single-region change in each direction, positive; `NaN`
        if the bucket is empty).

    Notes
    -----
    All magnitudes are reported positive -- direction is carried by the
    bucket name (`_improved`/`_worsened`), not by sign. This sidesteps the
    `set_a - set_b` sign convention `get_metric_summary()` and
    `compare_site_allocation()` use, which would otherwise be ambiguous
    for a baseline diff that is naturally `candidate - baseline`.
    """
    current = np.asarray(current, dtype=float)
    baseline = np.asarray(baseline, dtype=float)
    delta = current - baseline  # negative = improved (cheaper)

    tol = max(meaningful_change_threshold, 1e-9)
    improved = delta < -tol
    worsened = delta > tol
    unchanged = ~improved & ~worsened

    regions_improved = int(improved.sum())
    regions_worsened = int(worsened.sum())
    regions_unchanged = int(unchanged.sum())

    max_reduction = -delta[improved].min() if regions_improved else np.nan
    max_increase = delta[worsened].max() if regions_worsened else np.nan

    if demand is None:
        demand_improved = np.nan
        demand_worsened = np.nan
        demand_unchanged = np.nan
        proportion_demand_improved = np.nan
        proportion_demand_worsened = np.nan
        total_demand = np.nan
        mean_reduction_among_improved = (
            -delta[improved].mean() if regions_improved else np.nan
        )
        mean_increase_among_worsened = (
            delta[worsened].mean() if regions_worsened else np.nan
        )
    else:
        demand = np.asarray(demand, dtype=float)
        total_demand = demand.sum()
        demand_improved = demand[improved].sum()
        demand_worsened = demand[worsened].sum()
        demand_unchanged = demand[unchanged].sum()

        if total_demand > 0:
            proportion_demand_improved = demand_improved / total_demand
            proportion_demand_worsened = demand_worsened / total_demand
        else:
            proportion_demand_improved = np.nan
            proportion_demand_worsened = np.nan

        mean_reduction_among_improved = (
            -np.average(delta[improved], weights=demand[improved])
            if demand_improved and not np.isnan(demand_improved)
            else np.nan
        )
        mean_increase_among_worsened = (
            np.average(delta[worsened], weights=demand[worsened])
            if demand_worsened and not np.isnan(demand_worsened)
            else np.nan
        )

    # Cast every numeric value to a native Python float (regions_* are
    # already native ints, above). Numpy >=2.0 reprs its scalar types as
    # e.g. np.float64(46907.0) rather than 46907.0 -- harmless once these
    # values sit inside a DataFrame column (which formats through its own
    # display logic regardless), but a returned-bare dict repr shows the
    # wrapper verbatim, which is exactly the case
    # `population_impact_summary()` hits when `as_dict=True`.
    return {
        "regions_improved": regions_improved,
        "regions_worsened": regions_worsened,
        "regions_unchanged": regions_unchanged,
        "demand_improved": float(demand_improved),
        "demand_worsened": float(demand_worsened),
        "demand_unchanged": float(demand_unchanged),
        "proportion_demand_improved": float(proportion_demand_improved),
        "proportion_demand_worsened": float(proportion_demand_worsened),
        "total_demand": float(total_demand),
        "mean_reduction_among_improved": float(mean_reduction_among_improved),
        "mean_increase_among_worsened": float(mean_increase_among_worsened),
        "max_reduction": float(max_reduction),
        "max_increase": float(max_increase),
    }


def _format_threshold(t):
    """
    Render a threshold value for use in a column name, e.g. `30 -> "30"`,
    `42.5 -> "42.5"`. Used to build `demand_beyond_threshold_<t>` /
    `regions_beyond_threshold_<t>` column names -- deliberately a single
    underscore before the value (not `__`, which is reserved for secondary
    travel-matrix/demand-scenario suffixes) so the two conventions can never
    collide, e.g. `demand_beyond_threshold_45__public_transport`.
    """
    return f"{float(t):g}"


def _split_bins_into_tertiles(unique_bins, disadvantaged_end=None):
    """
    Split a sorted list of equity-band values into three chunks, returning
    them ordered from MOST-disadvantaged to LEAST-disadvantaged.

    The two end chunks are always equal in size (`len(unique_bins) // 3`
    each); any bins left over from that division go to the ignored middle
    chunk rather than to either end, so the two ends being compared are
    never a different size from one another. E.g. for 10 IMD deciles
    (1-10), the split is `[1,2,3] / [4,5,6,7] / [8,9,10]` -- deciles 1-3
    vs 8-10, with the extra decile absorbed by the ignored middle rather
    than tipping one end to four bins.

    Equal band *counts* is not the same as equal *population*: with
    IMD deciles specifically (a national construct), the two end chunks
    can hold very different headcounts within a single local geography.
    This function does not correct for that -- it only guarantees the
    chunk sizes are equal.

    `disadvantaged_end` mirrors `add_equity_data()`'s parameter of the same
    name: "low" means the lowest band values are the most disadvantaged
    (e.g. IMD decile 1 = most deprived), "high" means the opposite. `None`
    (its default) is treated as "low" -- the assumption every pre-existing
    caller of this arithmetic hardcoded, so behaviour is unchanged for any
    problem that never specified `disadvantaged_end`; only a problem that
    explicitly set `disadvantaged_end="high"` gets a (correct) different
    tertile ordering than before.

    Parameters
    ----------
    unique_bins : sequence
        Sorted, distinct equity-band values (e.g. IMD deciles 1-10).
    disadvantaged_end : {"low", "high", None}, optional

    Returns
    -------
    (list, list, list) or (None, None, None)
        `(most_disadvantaged, middle, least_disadvantaged)` chunks, or
        `(None, None, None)` if fewer than 3 distinct bins were given.
    """
    if len(unique_bins) < 3:
        return None, None, None

    bins = list(unique_bins)
    end_size = len(bins) // 3
    chunks = (bins[:end_size], bins[end_size : len(bins) - end_size], bins[len(bins) - end_size :])
    if disadvantaged_end == "high":
        chunks = tuple(reversed(chunks))

    return list(chunks[0]), list(chunks[1]), list(chunks[2])


def _order_bins_most_to_least_disadvantaged(unique_bins, disadvantaged_end):
    """
    Order `unique_bins` (already `sorted()`) most- to least-disadvantaged
    per `add_equity_data(disadvantaged_end=...)`, individually rather than
    bucketed into thirds -- built on `_split_bins_into_tertiles()`'s own
    ordering so the two never drift apart.

    Falls back to a plain reversal when there are too few distinct bands
    to split into tertiles at all (`_split_bins_into_tertiles` then returns
    `(None, None, None)`) but `disadvantaged_end="high"` -- without this,
    that case would silently fall back to ascending raw-bin order (least-
    disadvantaged first), which is exactly backwards.

    Parameters
    ----------
    unique_bins : sequence
        Sorted, distinct equity-band values (e.g. IMD deciles 1-10).
    disadvantaged_end : {"low", "high", None}, optional

    Returns
    -------
    list
        `unique_bins`, reordered most- to least-disadvantaged.
    """
    lower, middle, upper = _split_bins_into_tertiles(unique_bins, disadvantaged_end)
    if lower is not None:
        return lower + middle + upper
    if disadvantaged_end == "high":
        return list(reversed(unique_bins))
    return list(unique_bins)


def _is_maximise_metric(col):
    """
    True for solution metrics where a HIGHER value is better.

    Every other reported metric is a travel cost, where lower is better, so
    the coverage proportions and the "improvement" side of the population-
    impact metrics (see `_population_impact_metrics`) are the only
    maximisation objectives -- a bigger improved/reduced number is good, a
    bigger worsened/increased number is bad.

    Matches on a substring rather than the exact column name so that it also
    covers the `regions` variant and any `__<label>` secondary-travel-matrix
    suffix -- the exact-equality checks this replaced silently treated
    `proportion_within_coverage_threshold__<label>` as a minimisation
    objective, sorting secondary-matrix coverage backwards.

    `demand_unchanged`/`regions_unchanged` are directionless (neither a
    higher nor lower count is inherently "better") and are treated as
    lower-is-better here purely by omission; they are not meaningful
    `rank_on`/`sort_by` targets either way.

    Parameters
    ----------
    col : str
        Name of a column in `solution_df`.

    Returns
    -------
    bool
    """
    if not isinstance(col, str):
        return False
    return (
        "within_coverage_threshold" in col
        or "improved" in col
        or "reduction" in col
    )


# Temporary column holding the lower-is-better view of whatever metric a
# solve() is ranking on. Written just before a sort/prune and dropped
# immediately after, so it never reaches `solution_df` -- it is fully
# derivable from the ranking column and the resolved `Metric`.
_RANK_SCORE_COL = "_rank_score"


def _add_rank_score_column(df, scorer, output_col=_RANK_SCORE_COL):
    """
    Add a column holding `scorer`'s lower-is-better view of its ranking
    column, so a batch can be sorted/pruned with a plain ascending sort.

    Sorting on a normalised column rather than flipping an `ascending` flag
    is what lets `solve(rank_on=...)` accept a `closest_to_target` metric:
    "best" there is neither the largest nor the smallest raw value, so no
    choice of `ascending` can express it. It also, correctly, ties values
    equidistant from the target (an inter-tertile ratio of 0.8 and one of
    1.2 are equally far from parity) -- the caller's tie-breaker column
    then separates them.

    Returns
    -------
    tuple[pandas.DataFrame, str]
        A copy of `df` with the column added, and the column's name (so
        call sites can use it exactly like `_apply_cost_weighting`'s).
    """
    df = df.copy()
    df[output_col] = scorer.normalise(df[scorer.column].astype(float))
    return df, output_col


def _sort_solutions_by_metric(solution_df, sort_by):
    """
    Sort a solutions dataframe so the BEST solution for `sort_by` is first.

    Every `sort_by` call site used to sort with a bare
    `solution_df.sort_values(sort_by)`, i.e. always ascending. That is right
    for the travel-cost metrics but backwards for the coverage proportions,
    where higher is better -- so asking for the best solution by coverage
    returned the worst-covering one. Direction is resolved per column by
    `_is_maximise_metric`.

    Parameters
    ----------
    solution_df : pandas.DataFrame
        A solutions dataframe (or any frame containing `sort_by`).
    sort_by : str or sequence of str
        Name of the metric column to rank by, or several for a primary
        metric plus tie-breakers. Direction is resolved per column, so a
        coverage metric can be tie-broken by a travel cost and each is still
        sorted the right way round.

    Returns
    -------
    pandas.DataFrame
        Sorted copy, best first.

    Notes
    -----
    `kind="mergesort"` is a stable sort, so solutions tied on `sort_by` keep
    the relative order they already had rather than being reshuffled
    arbitrarily. Ties are routine here -- on the sample Brighton problem
    `max` takes only 5 distinct values across 15 candidate combinations --
    and pandas' default ("quicksort") is not stable, so without this the
    solution reported as "best" could differ between runs, machines or
    library versions purely by which tied row landed first.

    pandas only honours `kind` when sorting on a single column; multi-column
    sorts go through `lexsort_indexer`, which is stable already. Passing it
    unconditionally is therefore belt-and-braces for the multi-column case,
    and load-bearing for the single-column one.
    """
    columns = [sort_by] if isinstance(sort_by, str) else list(sort_by)
    return solution_df.sort_values(
        columns,
        ascending=[not _is_maximise_metric(col) for col in columns],
        kind="mergesort",
    )


def _min_max_normalize(series, constant_fill=0.0):
    """
    Min-max normalize a numeric series to a 0.0-1.0 scale, where the lowest
    value maps to 0.0 and the highest to 1.0.

    Parameters
    ----------
    series : pandas.Series
        The values to normalize.
    constant_fill : float, default 0.0
        The value every entry is set to when `series` has no range to
        normalize against (i.e. every value is identical). Callers pick
        this based on how the normalized result is used -- e.g. 0.0 for a
        "badness" scale where a tie should look as good as possible, or 1.0
        for a "weight" scale where a tie should contribute a full, neutral
        weight.

    Returns
    -------
    pandas.Series
        The normalized series, indexed the same as `series`.
    """
    lo, hi = series.min(), series.max()
    if hi == lo:
        return pd.Series(constant_fill, index=series.index)
    return (series - lo) / (hi - lo)


def _apply_cost_weighting(
    df,
    ranking_col,
    weights,
    scorer,
    cost_col="total_cost",
    output_col="composite_score",
):
    """
    Blend a batch of evaluated combinations' primary ranking column with
    their total_cost, via batch-relative min-max normalization -- but only
    when a positive 'cost' weight is present in `weights`. No-ops (returns
    `df` and `ranking_col` unchanged) otherwise, which is what guarantees
    site cost never influences a solution unless explicitly requested via
    weights={"cost": ...}.

    The resulting `output_col` is always on a "lower is better" (0=best)
    scale, regardless of the underlying objective's direction.

    Parameters
    ----------
    df : pandas.DataFrame
        A batch of evaluated combinations to compare against each other.
        Must contain `ranking_col` and (if cost weighting is active)
        `cost_col`.
    ranking_col : str
        The column holding each combination's primary objective value.
    weights : dict or None
        The (already-normalised) weights dict passed to `solve()`.
    scorer : Metric
        Describes the direction of `ranking_col`, via
        `Metric.normalise()`. Takes the *raw* column and owns its
        normalisation, so callers must pass the unnormalised values.
    cost_col : str, default "total_cost"
        The column holding each combination's total site cost.
    output_col : str, default "composite_score"
        The name of the blended score column to add to `df`.

    Returns
    -------
    tuple[pandas.DataFrame, str]
        The (possibly unmodified) DataFrame, and the name of the column
        that should be used for ranking/sorting/comparison from here on.
    """
    cost_weight = (weights or {}).get("cost", 0.0)
    if (
        not cost_weight
        or cost_col not in df.columns
        or df[cost_col].isna().all()
        or len(df) == 0
    ):
        return df, ranking_col

    # `Metric.normalise` already returns a lower-is-better view of the
    # column, so a plain min-max on top of it lands on the 0=best "badness"
    # scale for every direction. This replaces an `invert=higher_is_better`
    # flag, which could only express the two-way split and so had no way to
    # represent a `closest_to_target` rank_on. It is exactly equivalent for
    # the two directions that flag could express: for higher-is-better,
    # minmax(-x) == 1 - minmax(x), which is what inverting used to compute.
    primary_badness = _min_max_normalize(
        scorer.normalise(df[ranking_col].astype(float)), constant_fill=0.0
    )
    cost_badness = _min_max_normalize(df[cost_col].astype(float), constant_fill=0.0)

    df = df.copy()
    df[output_col] = (1.0 - cost_weight) * primary_badness + cost_weight * cost_badness
    return df, output_col


def _too_similar_to_accepted(
    new_set: set,
    accepted_sets: list[set],
    min_jaccard_distance: float,
) -> bool:
    """
    Returns True if new_set is too similar to any previously accepted solution.
    """
    if min_jaccard_distance == 0.0:
        return new_set in accepted_sets
    if min_jaccard_distance < 0:
        raise ValueError("Minimum jaccard distance cannot be negative")

    p = len(new_set)
    for existing_set in accepted_sets:
        intersection = len(new_set & existing_set)

        # [UPDATED] Fixed-size sets math optimization
        union = (2 * p) - intersection

        if union == 0:
            continue

        similarity = intersection / union
        distance = 1.0 - similarity
        if distance < min_jaccard_distance:
            return True

    return False


def _validate_capacity_constraint(self):
    total_demand = self.demand_data[self._demand_data_demand_col].sum()
    total_capacity = self.candidate_sites[self._candidate_sites_capacity_col].sum()

    if total_demand > total_capacity:
        raise ValueError(
            f"Insufficient Capacity! Your region has {total_demand} patients "
            f"but only {total_capacity} total slots. You need to add more "
            "candidate sites or increase 'p'."
        )


def _resolve_site_numeric_column(
    candidate_sites,
    candidate_id_col,
    col,
    site_names,
    param_name,
    quantity_label,
    allow_missing=False,
):
    """
    Validate and return a numeric per-site column from `candidate_sites`,
    indexed by `site_names` in the order given.

    Shared by `SFCAMixin._resolve_supply` (2SFCA's `supply_col`, always
    `allow_missing=False` -- a missing supply value would silently corrupt
    every region's accessibility score) and `SiteSolutionSet.
    site_capacity_summary()` (`capacity_col`, `allow_missing=True` -- a
    missing capacity is row-local, and `candidate_sites` legitimately mixes
    already-operating sites with not-yet-built proposals that have no
    capacity figure yet).

    Parameters
    ----------
    candidate_sites : pandas.DataFrame
    candidate_id_col : str
    col : str
        The column to resolve, e.g. a `supply_col` or `capacity_col` value.
    site_names : list of str
        Sites to resolve the column for, in this order.
    param_name : str
        The caller's parameter name for `col`, e.g. "supply_col" or
        "capacity_col" -- used verbatim in every raised message.
    quantity_label : str
        A short noun phrase for what the column represents, e.g. "supply
        quantity" or "capacity" -- used in the negative-value message.
    allow_missing : bool, default False
        If False (2SFCA's behaviour), a NaN value anywhere in the resolved
        column raises. If True, NaN values are returned as-is; the caller
        is responsible for handling them (typically: propagating to NaN in
        a derived ratio, and warning).

    Returns
    -------
    pandas.Series
        Indexed by `site_names`, in that order.

    Raises
    ------
    ValueError
        If `col` is not a column of `candidate_sites`, or if any resolved
        value is negative, or (when `allow_missing=False`) if any resolved
        value is NaN.
    KeyError
        If any of `site_names` is not in `candidate_sites`.
    TypeError
        If the column is not numeric.
    """
    if col not in candidate_sites.columns:
        raise ValueError(
            f"{param_name}={col!r} not found in candidate_sites. "
            f"Available columns: {list(candidate_sites.columns)}."
        )

    indexed = candidate_sites.set_index(candidate_id_col)[col]

    missing = [s for s in site_names if s not in indexed.index]
    if missing:
        raise KeyError(f"Sites not found in candidate_sites: {missing}.")

    resolved = indexed.loc[site_names]

    if not pd.api.types.is_numeric_dtype(resolved):
        raise TypeError(
            f"{param_name}={col!r} must contain numeric values. "
            "Hint: try pd.to_numeric() on this column before calling "
            "add_sites()."
        )

    if not allow_missing:
        null_sites = resolved[resolved.isna()].index.tolist()
        if null_sites:
            raise ValueError(
                f"The following sites are missing a value in "
                f"{param_name}={col!r}: {null_sites}."
            )

    negative_sites = resolved[resolved < 0].index.tolist()
    if negative_sites:
        raise ValueError(
            f"The following sites have a negative value in "
            f"{param_name}={col!r}, which is not a valid {quantity_label}: "
            f"{negative_sites}."
        )

    return resolved


def _wrap_label(text, width):
    if width is None or not isinstance(text, str):
        return text
    return "\n".join(textwrap.wrap(text, width=width))


def _add_rank_column(df, score_col, tiebreaker_col, ascending=True):
    """
    Add a sequential rank column based on a primary score and a tiebreaker.

    Rows are ranked by:
    1. `score_col` (primary ordering)
    2. `tiebreaker_col` (used to break ties deterministically)

    The resulting rank:
    - Is a "dense rank" (1, 2, 2, 3, ...)
    - Has no gaps
    - Assigns the exact same rank to true ties (identical score AND tiebreaker)

    Parameters
    ----------
    df : pandas.DataFrame
        Input DataFrame.
    score_col : str
        Column used as the primary ranking metric.
    tiebreaker_col : str
        Column used to break ties when `score_col` values are equal.
    ascending : bool or list of bool, default True
        Sort direction. If a single bool, applied to both columns.
        If a list, should match [score_col, tiebreaker_col].

        Example:
        - ascending=[True, True] -> lower is better for both
        - ascending=[False, True] -> higher score is better, lower tiebreaker is better

    Returns
    -------
    pandas.DataFrame
        A new DataFrame with `solution_rank` inserted as the first column.
    """

    # Normalise ascending argument
    if isinstance(ascending, bool):
        ascending = [ascending, ascending]

    # 1. Sort by primary score, then tiebreaker
    # sort_values returns a new DataFrame, so we don't strictly need .copy()
    # kind="mergesort" keeps rows tied on BOTH columns in their existing
    # order. Multi-column sorts already go through a stable lexsort, so this
    # is belt-and-braces today -- it matters if this is ever reduced to a
    # single sort column. See _sort_solutions_by_metric for the full note.
    ranked_df = df.sort_values(
        [score_col, tiebreaker_col], ascending=ascending, kind="mergesort"
    )

    # 2. Assign dense ranks that handle true ties
    # sort=False ensures groupby respects the order we just established.
    # ngroup() numbers each unique group starting from 0, so we add 1.
    ranked_df["solution_rank"] = (
        ranked_df.groupby([score_col, tiebreaker_col], sort=False).ngroup() + 1
    )

    # 3. Move rank column to the front
    ranked_df.insert(0, "solution_rank", ranked_df.pop("solution_rank"))

    return ranked_df.reset_index(drop=True)


def _select_solution(
    solution_df, sort_by=None, solution_rank=1, site_names=None, site_indices=None
):
    """
    Select a single solution from solution_df based on provided criteria.

    Priority: site_indices > site_names > sort_by/solution_rank

    Returns
    -------
    pd.DataFrame
        Single-row DataFrame containing the selected solution.

    Raises
    ------
    ValueError
        If no matching solution is found or if solution_rank is out of range.
    """
    # Priority 1: site_indices
    if site_indices is not None:
        site_indices = np.asarray(site_indices)  # handle list input
        mask = solution_df["site_indices"].apply(
            lambda x: np.array_equal(np.sort(x), np.sort(site_indices))
        )
        filtered = solution_df[mask]
        if filtered.empty:
            raise ValueError(f"No solution found with site_indices: {site_indices}")
        return filtered.head(1).reset_index()

    # Priority 2: site_names
    if site_names is not None:
        site_names_sorted = sorted(site_names)
        mask = solution_df["site_names"].apply(lambda x: sorted(x) == site_names_sorted)
        filtered = solution_df[mask]
        if filtered.empty:
            raise ValueError(f"No solution found with site_names: {site_names}")
        return filtered.head(1).reset_index()

    # Priority 3: rank-based selection
    if sort_by is not None:
        sorted_df = _sort_solutions_by_metric(solution_df, sort_by)
    else:
        sorted_df = solution_df

    if solution_rank < 1 or solution_rank > len(sorted_df):
        raise ValueError(
            f"solution_rank must be between 1 and {len(sorted_df)}, got {solution_rank}"
        )

    return sorted_df.iloc[[solution_rank - 1]].reset_index()


def _get_ordinal_suffix(n):
    """
    Return the ordinal suffix for a number (e.g., 'st', 'nd', 'rd', 'th').

    Parameters
    ----------
    n : int
        The number to get the suffix for.

    Returns
    -------
    str
        The ordinal suffix ('st', 'nd', 'rd', or 'th').
    """
    if 10 <= n % 100 <= 20:
        return "th"
    else:
        return {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")


def _unreachable_metrics_fragment(regions_unreachable):
    """
    "N regions unreachable" (singular-aware), or "" when `regions_
    unreachable` is 0 -- for appending to a plot title/label wherever the
    honest, reachable-only travel-cost metrics (weighted_average, max,
    ...) are already being reported alongside it. Without this, a demand
    location with no feasible journey (`add_travel_matrix(allow_missing=
    True)`) simply disappears from a plot's summary text with no
    indication anything was excluded.

    Parameters
    ----------
    regions_unreachable : int
        `solution_df`'s `regions_unreachable` value (or its `__<label>`
        secondary-matrix variant) for the solution being plotted.

    Returns
    -------
    str
    """
    n = int(regions_unreachable)
    if n == 0:
        return ""
    region_word = "region" if n == 1 else "regions"
    return f"{n} {region_word} unreachable"


def _reject_removed_basemap_alias(kwargs, method_name):
    """
    Raise a clear error if the removed `show_basemap` argument is passed.

    `plot_region_geometry_layer`, `plot_hotspots` and `plot_quadrant_map`
    spelled this flag `show_basemap` until v0.7.0, when `add_basemap`
    became the name on every plotting method. `show_basemap` was removed
    rather than aliased.

    This guard exists because those methods also accept `**kwargs` and
    forward them to the underlying plotting call, so a removed argument
    does not produce a normal "unexpected keyword argument" TypeError
    naming the method. Instead it reaches matplotlib and surfaces as
    ``AttributeError: PatchCollection.set() got an unexpected keyword
    argument 'show_basemap'`` on static plots, or is ignored outright on
    interactive ones, since ``GeoDataFrame.explore()`` tolerates unknown
    keywords. Neither tells the caller what to do about it.

    Parameters
    ----------
    kwargs : dict
        The calling method's `**kwargs`, checked for the removed name.
    method_name : str
        Name of the calling method, used in the error message.

    Raises
    ------
    TypeError
        If `show_basemap` is present.
    """
    if "show_basemap" in kwargs:
        raise TypeError(
            f"{method_name}() no longer accepts 'show_basemap', which was "
            "removed in v0.7.0. Use 'add_basemap' instead -- it behaves "
            "identically and is now the argument name on every plotting "
            "method."
        )


def _colours_and_styles(n: int, palette: str):
    """
    Return n (colour, linestyle, marker) tuples for a given palette name.

    Qualitative palettes (tab10, Set2, Dark2, ...) have a small fixed
    number of genuinely distinct colours. If more lines are needed than
    the palette provides, colours are cycled and paired with a different
    linestyle/marker each time round, so repeated colours stay visually
    distinguishable rather than becoming ambiguous duplicates. Continuous
    palettes (viridis, husl, mako, ...) generate a fresh distinct colour
    per line and never need to cycle.
    """
    try:
        cmap = plt.get_cmap(palette)
        is_qualitative = cmap.N < 256  # matplotlib's convention for discrete cmaps
        n_native = cmap.N if is_qualitative else n
    except ValueError:
        # seaborn-only palette names (husl, hls, ...) generate n evenly
        # spaced distinct hues on demand -- no fixed palette size, so
        # there's never a need to cycle
        n_native = n

    if n <= n_native:
        colours = sns.color_palette(palette, n_colors=n)
        return list(zip(colours, ["-"] * n, ["o"] * n))

    colours_base = sns.color_palette(palette, n_colors=n_native)
    linestyle_cycle = ["-", "--", "-.", ":"]
    marker_cycle = ["o", "s", "^", "D", "v", "P", "X"]
    out = []
    for i in range(n):
        cycle_pass = i // n_native
        out.append(
            (
                colours_base[i % n_native],
                linestyle_cycle[cycle_pass % len(linestyle_cycle)],
                marker_cycle[cycle_pass % len(marker_cycle)],
            )
        )
    return out
