import numpy as np
from itertools import combinations
from functools import wraps
import inspect
from pandas.api.types import is_numeric_dtype
import pandas as pd
import geopandas
from pathlib import Path
from urllib.parse import urlparse
import requests
from io import BytesIO
import textwrap
from warnings import warn

PANDAS_EXTS = [".csv", ".parquet", ".xlsx", ".xls"]
GEOPANDAS_EXTS = [".shp", ".geojson", ".gpkg"]

SUPPORTED_OBJECTIVES = [
    "p_median",
    "hybrid_p_median",
    "p_center",
    "simple_p_median",
    "hybrid_simple_p_median",
    "mclp",
]

PLANNED_OBJECTIVES = [
    "lscp",
    "lscp_b",
]

# Todo - update these as generated by Gemini with only minimal revisions so far
SOLVER_DEFINITIONS = {
    "simple_p_median": {
        "name": "P-Median (Average Distance Minimizer)",
        "goal": "Minimize the total travel distance or time.",
        "healthcare_context": "Best for situations like siting a series of storage hubs efficiently across a region where demand/volume doesn't matter.",
        "trade_off": "Can leave remote or rural patients with very long travel times in favor of urban density.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "p_median": {
        "name": "P-Median (Average Weighted Distance Minimizer)",
        "goal": "Minimize the total travel distance or time for the entire population, weighting the travel times by a metric such as demand per region.",
        "healthcare_context": "Best for general primary care where you want the 'average' patient to have the shortest trip possible.",
        "trade_off": "Can leave remote or rural patients with very long travel times in favor of urban density.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "hybrid_simple_p_median": {
        "name": "Hybrid Simple P-Median (The Safety Net Model)",
        "goal": "Minimize the total travel distance or time, weighting the travel times by a metric such as demand per region, while guaranteeing a maximum 'cutoff' time for every patient.",
        "healthcare_context": "Makes the system efficient while preventing major 'postcode lotteries' where some patients travel a very long way.",
        "trade_off": "Hard cut-off point could see some good solutions that nearly meet the cutoff being discarded.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "hybrid_p_median": {
        "name": "Hybrid P-Median (The Safety Net Model)",
        "goal": "Minimize average travel distance or time while guaranteeing a maximum 'cutoff' time for every patient.",
        "healthcare_context": "Makes the system efficient while preventing major 'postcode lotteries' where some patients travel a very long way.",
        "trade_off": "Hard cut-off point could see some good solutions that nearly meet the cutoff being discarded.",
        "status": "Supported",
        "academic_ref": "ReVelle & Swain (1970)",
    },
    "p_center": {
        "name": "P-Center (The Fair-Maximum Model)",
        "goal": "Minimize the maximum travel distance or time for the furthest patient.",
        "healthcare_context": "Best for ensuring universal access in rural regions; 'No one left behind'.",
        "trade_off": "Can lead to higher average travel distances or times for the majority population.",
        "status": "Supported",
        "academic_ref": "Suzuki & Drezner (1996)",
    },
    "mclp": {
        "name": "Maximal Coverage Location Problem (MCLP)",
        "goal": "Maximize the number of people within a specific time/distance 'threshold' (e.g., 15 minutes).",
        "healthcare_context": "Best for emergency services (Ambulance/ER) where getting there within a 'Golden Hour' is more important than the average trip time.",
        "trade_off": "Does not care how far away people are once they are outside the threshold.",
        "status": "Supported",
        "academic_ref": "Church & ReVelle (1974)",
    },
    "lscp": {
        "name": "Location Set Covering Location Problem (LSCP)",
        "goal": "Find the minimum number of facilities needed to cover *everyone* within a certain distance.",
        "healthcare_context": "Best for universal mandates (e.g., ensuring every citizen is within 20 miles of a pharmacy).",
        "trade_off": "Can be very expensive as it forces clinics into sparsely populated areas to reach the final 1%.",
        "status": "Planned",
        "academic_ref": "Toregas et al. (1971)",
    },
    "lscp-b": {
        "name": "LSCP-B (Backup Coverage Model)",
        "goal": "Minimize the number of facilities needed to ensure everyone is covered by AT LEAST TWO locations.",
        "healthcare_context": "Critical for high-reliability services like Maternity units or Stroke centers where 'System Busy' is a life-threatening risk.",
        "trade_off": "Requires significantly more resources (budget/staff) than standard coverage to achieve the same geographic footprint.",
        "status": "Planned",
        "academic_ref": "Hogan & ReVelle (1986), Church & Murray (2018)",
    },
}


ALGORITHM_DEFINITIONS = {
    "brute_force": {
        "name": "Brute Force (Exact Search)",
        "mechanism": "Checks every single possible combination of sites mathematically available.",
        "trade_off": "Computationally explosive. Adding just a few more sites can increase solve time from seconds to years. Use only for very small projects (e.g., picking 3 sites out of 10). Guaranteed to find the 'Global Optimum'.",
        "status": "Supported",
    },
    "random_restarts": {
        "name": "Random Restarts",
        "mechanism": "Runs a local search multiple times, each time starting from a completely different random set of sites.",
        "healthcare_context": "Provides the 'Portfolio of Options' managers need. It explores the map more widely to find diverse 'good' solutions.",
        "trade_off": "Diminishing returns; eventually, you're just using time and computational resources to find the same few solutions again.",
        "status": "Planned",
    },
    "greedy_add": {
        "name": "Greedy Addition",
        "mechanism": "Starts with zero sites and adds the single best location one-by-one until the target is reached.",
        "trade_off": "Short-sighted; it never re-evaluates early choices, which might lead to a sub-optimal final network.",
        "status": "Planned",
    },
    "local_search_swap": {
        "name": "Local Search (The Swap Heuristic)",
        "mechanism": "Starts with a solution and tries swapping one active site for an inactive one to see if it improves the score. Also known as 'Teitz-Bart' or the 'hill-climbing' algorithm.",
        "trade_off": "Prone to getting stuck in 'Local Optima'—it finds a good solution but might miss a radically different, better one.",
        "status": "Planned",
    },
    "grasp": {
        "name": "GRASP (Greedy Randomized Adaptive Search Procedure)",
        "mechanism": "A mix of greedy and random: it picks from a 'restricted candidate list' of the top few best moves at each step. It finds solutions that are high-performing but non-obvious, avoiding the 'predictable' greedy paths.",
        "trade_off": "Requires tuning the 'greediness' parameter. If too random, it’s aimless; if too greedy, it lacks diversity.",
        "status": "Planned",
    },
}


def _check_crs_match(gdf_1, gdf_2, strict=False):
    """
    Check that the coordinate reference system of two geodataframes is the same and warn if it is not
    """
    try:
        if strict:
            assert gdf_1.crs == gdf_2.crs, f"CRS Mismatch. {gdf_1.crs} vs {gdf_2.crs}."
        else:
            return gdf_1.crs == gdf_2.crs
    except AttributeError:
        warn(f"Could not check crs. CRS 1: {gdf_1.crs}. CRS 2: {gdf_2.crs}")


def _check_crs_match_pref(gdf, pref, strict=False):
    if strict:
        assert gdf.crs.to_string() == pref, (
            f"CRS Mismatch. {gdf.crs.to_string()} vs {pref}."
        )
    else:
        return gdf.crs.to_string() == pref


def _guess_crs(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    sample_size: int = 1000,
    verbose: bool = True,
):
    """
    Guess CRS (EPSG:4326 or EPSG:27700) from coordinate columns and return a GeoDataFrame.

    Parameters
    ----------
    df : pd.DataFrame
    x_col : str
        Column containing longitude or easting
    y_col : str
        Column containing latitude or northing
    sample_size : int
        Number of rows to sample for inference
    verbose : bool
        Whether to print reasoning

    Returns
    -------
    geopandas.GeoDataFrame
        GeoDataFrame with guessed CRS

    Raises
    ------
    ValueError
        If CRS cannot be confidently determined
    """

    # Drop NA and sample
    sample = df[[x_col, y_col]].dropna().head(sample_size)

    x = sample[x_col]
    y = sample[y_col]

    # Heuristic checks
    is_latlon = x.between(-180, 180).all() and y.between(-90, 90).all()

    is_bng = x.between(0, 700000).all() and y.between(0, 1300000).all()

    # Optional tighter UK bounds (improves confidence)
    is_bng_tight = (
        x.between(0, 700000).all()
        and y.between(0, 1300000).all()
        and x.mean() > 100000
        and x.mean() < 700000
        and y.mean() > 0
        and y.mean() < 1300000
    )

    if is_latlon and not is_bng:
        crs = "EPSG:4326"
        reason = "Values fall within longitude/latitude bounds"

    elif is_bng_tight and not is_latlon:
        crs = "EPSG:27700"
        reason = "Values fall within British National Grid bounds"

    elif is_bng and not is_latlon:
        crs = "EPSG:27700"
        reason = "Values look like projected coordinates (BNG range)"

    else:
        raise ValueError(
            "Unable to confidently determine CRS. Please specify manually."
        )

    if verbose:
        print(f"Guessed CRS: {crs} ({reason})")

    return crs


def _convert_crs(df, target_crs):
    return df.to_crs(target_crs)


def _validate_columns(
    df,
    col_names,
    numeric_col_names=None,
    msg_template=None,
    context=None,
):
    if not isinstance(df, (pd.DataFrame, geopandas.GeoDataFrame)):
        raise TypeError(
            f"Passed a {type(df)} where a Pandas or Geopandas dataframe was expected."
        )

    if numeric_col_names is None:
        numeric_col_names = []

    # --- 1. Check for Missing Columns ---
    missing = [c for c in col_names if c not in df.columns]

    if missing:
        if msg_template:
            error_msg = msg_template.format(missing=missing, available=list(df.columns))
        else:
            context_str = f" in {context}" if context else ""
            error_msg = (
                f"Missing columns{context_str}: {missing}. Found columns: {df.columns}"
            )
        raise ValueError(error_msg)

    # --- 2. Check for Numeric Data Types ---
    non_numeric = [
        col
        for col in numeric_col_names
        if col in df.columns and not is_numeric_dtype(df[col])
    ]

    if non_numeric:
        raise TypeError(
            f"Data Type Error: The following columns must contain numbers (integers or floats), "
            f"but they contain other types (like strings): {non_numeric}. "
            "Hint: Try using pd.to_numeric() on these columns before passing them in."
        )


def _generate_all_combinations(
    n_facilities: int, p: int, site_problem=None, force_include_indices=None
) -> list:
    """
    Generate all possible permutations of a list without replacement.

    n_facilities: int
        The total number of facilities that exist

    p: int
        The number of candidate solutions
    """

    # Code modified from https://github.com/health-data-science-OR/healthcare-logistics
    # Credit for original code to Dr Tom Monks
    # Licence reproduced below in line with reuse conditions
    # MIT License
    #
    # Copyright (c) 2020 health-data-science-OR
    #
    # Permission is hereby granted, free of charge, to any person obtaining a copy
    # of this software and associated documentation files (the "Software"), to deal
    # in the Software without restriction, including without limitation the rights
    # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    # copies of the Software, and to permit persons to whom the Software is
    # furnished to do so, subject to the following conditions:
    #
    # The above copyright notice and this permission notice shall be included in all
    # copies or substantial portions of the Software.
    #
    # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    # SOFTWARE.

    facility = np.arange(n_facilities, dtype=int)
    result = [np.array(a) for a in combinations(facility, p)]

    # if site_problem is not None and force_include_indices is not None:
    #     raise ValueError(
    #         "Dev error: please provide only one of site_problem or"
    #         "force_include_indices to _generate_all_combinations()"
    #     )

    if site_problem is not None:
        if site_problem._candidate_sites_required_sites_col is not None:
            # Define a set of sensible "truthy" values (all lowercase)
            truthy_values = {"y", "yes", "true", "t", "required", "1"}

            # Normalize the column data: convert to string, lowercase, and strip whitespace
            # This prevents errors if the column contains actual booleans, integers, or messy strings
            col_data = (
                site_problem.candidate_sites[
                    site_problem._candidate_sites_required_sites_col
                ]
                .astype(str)
                .str.lower()
                .str.strip()
            )

            # Create the boolean mask using .isin()
            is_required = col_data.isin(truthy_values)

            # Extract the integer indices (e.g., [0, 1, 2])
            site_indices = np.where(is_required)[0]

            # Convert required indices to a set for O(1) lookups
            required_set = set(site_indices)

            # Filter the combinations to only keep those containing ALL required sites
            result = [a for a in result if required_set.issubset(a)]

    if force_include_indices is not None:
        # Convert required indices to a set for O(1) lookups
        required_set = set(force_include_indices)

        # Filter the combinations to only keep those containing ALL required sites
        result = [a for a in result if required_set.issubset(a)]

    return result


def _try_drop(df, drop_cols):
    if drop_cols:
        missing_cols = [col for col in drop_cols if col not in df.columns]

        if missing_cols:
            raise ValueError(
                f"The following columns were not found in the GeoDataFrame: {missing_cols}"
            )

        try:
            df = df.drop(columns=drop_cols)
        except Exception as e:
            raise ValueError(
                f"Failed to drop columns {drop_cols} from GeoDataFrame."
            ) from e

    return df


def _load_spatial_or_tabular_data(data_input, skip_cols=None):
    """
    Takes a file path, URL, file-like object, or a DataFrame and returns the loaded DataFrame
    alongside a string indicating its spatial type. Supports GitHub raw content conversion.
    """

    # 1. Handle existing DataFrames
    if isinstance(data_input, geopandas.GeoDataFrame):
        return _try_drop(data_input, skip_cols), "geopandas"
    if isinstance(data_input, pd.DataFrame):
        return _try_drop(data_input, skip_cols), "pandas"

    content = data_input
    ext = ""

    # 2. Handle Strings (URLs or Local Paths)
    if isinstance(data_input, (str, Path)):
        data_str = str(data_input)
        parsed = urlparse(data_str)

        if parsed.scheme in ("http", "https"):
            # Normalize GitHub URLs to raw content
            if "github.com" in data_str and "/blob/" in data_str:
                data_str = data_str.replace(
                    "github.com", "raw.githubusercontent.com"
                ).replace("/blob/", "/")

            # Fetch content
            response = requests.get(data_str, allow_redirects=True)
            response.raise_for_status()

            content = BytesIO(response.content)
            # Get extension from the actual URL path, not the redirecting one
            ext = Path(urlparse(data_str).path).suffix.lower()
        else:
            path = Path(data_input)
            if not path.exists():
                raise FileNotFoundError(f"I couldn't find a file at: {path}")
            content = path
            ext = path.suffix.lower()

    # 3. Handle File-like objects
    elif hasattr(data_input, "read"):
        content = data_input
        name = getattr(data_input, "name", "")
        ext = Path(name).suffix.lower()

    else:
        raise TypeError(
            "Invalid input type. Provide a DataFrame, URL, path, or file-like object."
        )

    # --- Router: Read based on extension ---

    # Priority 1: GeoPandas
    if ext in GEOPANDAS_EXTS or ext == ".json":
        try:
            # We use content for GeoJSON/GPKG, etc.
            # Note: For .zip (Shapefiles), GeoPandas usually needs a path or specific handle
            df = geopandas.read_file(content)
            return _try_drop(df, skip_cols), "geopandas"
        except Exception as e:
            # If it failed but it's a JSON-like extension, it might just be a pandas-style JSON
            if ext not in {".geojson", ".shp"}:
                pass
            else:
                raise e

    # Priority 2: Pandas
    if ext in PANDAS_EXTS:
        if ext == ".csv":
            df = pd.read_csv(content)
        if ext == ".parquet":
            df = pd.read_parquet(content)
        if ext in [".xlsx", ".xls"]:
            df = pd.read_excel(content)

        return _try_drop(df, skip_cols), "pandas"

    # Final Fallback: Try GeoPandas anyway if extension is ambiguous
    try:
        df = geopandas.read_file(content)
        return _try_drop(df, skip_cols), "geopandas"
    except:
        raise ValueError(f"Could not parse data with extension '{ext}'.")


def _safe_evaluate(text_string, solution):
    try:
        return eval(f"f{repr(text_string)}", {}, {"solution": solution})
    except Exception:
        # fallback: treat as literal string
        return text_string


def _get_ranking_by_objective(objective):
    if objective in ["p_median", "hybrid_p_median"]:
        return "weighted_average"
    elif objective in ["simple_p_median", "hybrid_simple_p_median"]:
        return "unweighted_average"
    elif objective in ["p_center"]:
        return "max"
    elif objective in ["mclp"]:
        return "proportion_within_coverage_threshold"


def _too_similar_to_accepted(
    new_set: set,
    accepted_sets: list[set],
    min_jaccard_distance: float,
) -> bool:
    """
    Returns True if new_set is too similar to any previously accepted solution.
    """
    if min_jaccard_distance == 0.0:
        return new_set in accepted_sets
    if min_jaccard_distance < 0:
        raise ValueError("Minimum jaccard distance cannot be negative")

    p = len(new_set)
    for existing_set in accepted_sets:
        intersection = len(new_set & existing_set)

        # [UPDATED] Fixed-size sets math optimization
        union = (2 * p) - intersection

        if union == 0:
            continue

        similarity = intersection / union
        distance = 1.0 - similarity
        if distance < min_jaccard_distance:
            return True

    return False


def _validate_capacity_constraint(self):
    total_demand = self.demand_data[self._demand_data_demand_col].sum()
    total_capacity = self.candidate_sites[self._candidate_sites_capacity_col].sum()

    if total_demand > total_capacity:
        raise ValueError(
            f"Insufficient Capacity! Your region has {total_demand} patients "
            f"but only {total_capacity} total slots. You need to add more "
            "candidate sites or increase 'p'."
        )


def _wrap_label(text, width):
    if width is None or not isinstance(text, str):
        return text
    return "\n".join(textwrap.wrap(text, width=width))
